#!/bin/bash
# init script for the openQRM local-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/include/openqrm-plugin-local-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/etc/openqrm-plugin-local-storage.conf

PARTIMAGE_NG_LIBS="libparted,libext2fs,libntfs,libstdc++,libgcc_"

function copy_lib_dependencies() {
    local TARGET_LIB=$1
    local TARGET_DIR=$2
    LIB_FILE=`find /lib/ /usr/lib -maxdepth 2 -name $TARGET_LIB*so* -type f | grep -v vmware | grep -v "\-3g" | grep -v openqrm | head -n1`
    if [ "$LIB_FILE" == "" ]; then
    	echo "ERROR: Cloud not find $TARGET_LIB on this system ! Exiting..."
        return 1
    fi
    cp -aRv $LIB_FILE $TARGET_DIR/
    for LIB_LINK in `find /lib/ /usr/lib -maxdepth 2 -name $TARGET_LIB*so* -type l | grep -v vmware  | grep -v "\-3g" | grep -v openqrm`; do
        cp -aRv $LIB_LINK $TARGET_DIR/
    done
}


function openqrm_plugin_local_storage_start() {
	echo "Starting the openQRM local-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage/.running
}


function openqrm_plugin_local_storage_stop() {
	echo "Stopping the openQRM local-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage/.running
}

function openqrm_plugin_local_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "local-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "local-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM local-storage-plugin"
	openqrm_plugin_local_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD local-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-storage
    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.local-storage.php
    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/partimage-ng.tgz
}

function openqrm_plugin_local_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "local-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "local-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM local-storage-plugin"
    # need to gather the lib dependencies for partimage-ng, for now in the init phase
    rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/bin
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/lib
    cp -f $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bin/partimage-ng $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/bin/
    # cp lib deps
    OLDIFS=$IFS
    IFS=','
    for LIB_DEP in $PARTIMAGE_NG_LIBS; do
        IFS=$OLDIFS
        if ! copy_lib_dependencies $LIB_DEP $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/lib/; then
            return 1
        fi
    done
    IFS=$OLDIFS
    cd $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp/
    tar -czvf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/partimage-ng.tgz bin include lib
    cd - 1>/dev/null
    rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/bs-tmp

	openqrm_server_add_deployment_type $USERNAME $PASSWORD local-storage local-storage "Local-Disk deployment" local-storage "Local-Deployment Storage"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/root-mount.local-storage
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/root-mount.local-storage $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-storage
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/image.local-storage.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.local-storage.php
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/partimage-ng.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/partimage-ng.tgz
    # create storage dir for stat files
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/storage
    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/storage
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_local_storage_start
		;;
	stop)
		openqrm_plugin_local_storage_stop
		;;
	restart)
		openqrm_plugin_local_storage_stop
		sleep 1
		openqrm_plugin_local_storage_start
		;;
	init)
		openqrm_plugin_local_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_local_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




