#!/bin/bash
# init script for the openQRM local-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/include/openqrm-plugin-local-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/etc/openqrm-plugin-local-storage.conf
if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
	openqrm_server_get_config
	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
	OPENQRM_INTERFACE=$OPENQRM_SERVER_INTERFACE
	resource_id=0
	resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
elif [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
	. $OPENQRM_RESOURCE_PARAMETER_FILE
	OPENQRM_SERVER_IP=$resource_openqrmserver
	OPENQRM_INTERFACE=`ifconfig | grep -i $resource_mac | grep :oq | cut -d':' -f1`
fi



function openqrm_plugin_local_storage_start() {
	echo "Starting the openQRM local-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage/.running
}


function openqrm_plugin_local_storage_stop() {
	echo "Stopping the openQRM local-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage/.running
}

function openqrm_plugin_local_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "local-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "local-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM local-storage-plugin"
	openqrm_plugin_local_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD local-storage
	# removing the tables
	if ! wget -q -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "http://localhost/openqrm/base/plugins/local-storage/local-storage-action.php?local_storage_command=uninstall"; then
		local_storage_log init "ERROR: Could not remove the local-storage plugin tables in the database!"
	fi
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-storage
    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.local-storage.php
    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/local-storage-state.php
    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-local-storage.tgz
}

function openqrm_plugin_local_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "local-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "local-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM local-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD local-storage local-storage "Local-Disk deployment" local-storage "Local-Deployment Storage"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage
	# creating the tables
	if ! wget -q -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "http://localhost/openqrm/base/plugins/local-storage/local-storage-action.php?local_storage_command=init"; then
		local_storage_log init "ERROR: Could not create the local-storage plugin tables in the database!"
        rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/local-storage
		exit 1
	fi
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/root-mount.local-storage
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/root-mount.local-storage $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-storage
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/image.local-storage.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.local-storage.php
    ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/local-storage-state.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/local-storage-state.php
    ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/boot-service-local-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-local-storage.tgz
    # create storage dir for stat files
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/storage
    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-storage/web/storage
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_local_storage_start
		;;
	stop)
		openqrm_plugin_local_storage_stop
		;;
	restart)
		openqrm_plugin_local_storage_stop
		sleep 1
		openqrm_plugin_local_storage_start
		;;
	init)
		openqrm_plugin_local_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_local_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




