#!/bin/bash
# init script for the openQRM aoe-deployment-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-deployment/include/openqrm-plugin-aoe-deployment-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-deployment/etc/openqrm-plugin-aoe-deployment.conf


# TODO
# we must find a proper solution to start/stop 
# the plugin with correct user-authentication
# -> for now using openqrm user static

function openqrm_plugin_aoe-deployment_start() {
	echo "Starting the openQRM aoe-deployment-plugin"
	openqrm_server_add_deployment_type openqrm openqrm aoe "Aoe-root deployment"
}


function openqrm_plugin_aoe-deployment_stop() {
	echo "Stopping the openQRM aoe-deployment-plugin"
	openqrm_server_remove_deployment_type openqrm openqrm aoe

}

function openqrm_plugin_aoe-deployment_uninstall() {
	echo "Uninstalling the openQRM aoe-deployment-plugin"
	openqrm_plugin_aoe-deployment_stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.aoe-menu.html
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-interfaces
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-discover
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-stat
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf
}

function openqrm_plugin_aoe-deployment_init() {
	echo "Initializing the openQRM aoe-deployment-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-deployment/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-deployment/web/root-mount.aoe-deployment
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-deployment/web/root-mount.aoe-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-deployment
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-deployment/web/image-deployment-parameter.aoe-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.aoe-menu.html
	# copying aoe-interfaces to boot-service dir
	cp -f `which aoe-interfaces` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-discover to boot-service dir
	cp -f `which aoe-discover` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-stat to boot-service dir
	cp -f `which aoe-stat` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-mkdevs to boot-service dir
	cp -f `which aoe-mkdevs` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-mkshelf to boot-service dir
	cp -f `which aoe-mkshelf` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	
}


case "$1" in
	start)
		openqrm_plugin_aoe-deployment_start
		;;
	stop)
		openqrm_plugin_aoe-deployment_stop
		;;
	restart)
		openqrm_plugin_aoe-deployment_stop
		sleep 1
		openqrm_plugin_aoe-deployment_start
		;;
	init)
		openqrm_plugin_aoe-deployment_init
		;;
	uninstall)
		openqrm_plugin_aoe-deployment_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




