#!/bin/bash
# init script for the openQRM netapp-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/include/openqrm-plugin-netapp-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/etc/openqrm-plugin-netapp-storage.conf

function openqrm_plugin_netapp_storage_start() {
	echo "Starting the openQRM netapp-storage-plugin"
	openqrm_plugin_netapp_storage_stop 1>/dev/null 2>&1
}


function openqrm_plugin_netapp_storage_stop() {
	echo "Stopping the openQRM netapp-storage-plugin"
}

function openqrm_plugin_netapp_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "netapp-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "netapp-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM netapp-storage-plugin"
	openqrm_plugin_netapp_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD netapp-iscsi
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD netapp-nfs
	openqrm_server_remove_storagetype $USERNAME $PASSWORD netapp-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/netapp-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/storagetype-capabilities.netapp-storage-menu.html
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.netapp-iscsi-deployment 
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.netapp-nfs-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.netapp-iscsi-menu.html
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.netapp-nfs-menu.html

	# remove only if nfs/iscsi/aoe is not enabled
	if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep iscsi-storage 1>/dev/null 2>&1; then
		if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep lvm-storage 1>/dev/null 2>&1; then
			rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid
			rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm
		fi
	fi
}

function openqrm_plugin_netapp_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "lvm-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "lvm-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM netapp-storage-plugin"
	openqrm_server_add_storagetype $USERNAME $PASSWORD netapp-storage "NetApp Filer (nfs/iscsi)"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD netapp-iscsi "Iscsi-root deployment"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD netapp-nfs "Nfs-root deployment"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/netapp-storage
	# linking the storagetype-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/web/storagetype-capabilities.netapp-storage-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/storagetype-capabilities.netapp-storage-menu.html

	# linking the root mount hooks
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/web/root-mount.netapp-iscsi-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.netapp-iscsi-deployment
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/web/root-mount.netapp-nfs-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.netapp-nfs-deployment
	# linking the image deployment parameters menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/web/image-deployment-parameter.netapp-iscsi-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.netapp-iscsi-menu.html
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/netapp-storage/web/image-deployment-parameter.netapp-nfs-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.netapp-nfs-menu.html

	# copying iscsid to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid ]; then
		cp -f `which iscsid` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying iscsiadm to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm ]; then
		cp -f `which iscsiadm` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi

	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_netapp_storage_start
		;;
	stop)
		openqrm_plugin_netapp_storage_stop
		;;
	restart)
		openqrm_plugin_netapp_storage_stop
		sleep 1
		openqrm_plugin_netapp_storage_start
		;;
	init)
		openqrm_plugin_netapp_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_netapp_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




