#!/bin/bash
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

if [ -f plugins/sshterm/etc/build.conf/sshterm-component.conf ]; then
    PLUGIN_CONFS="plugins/kvm/etc/build.conf/kvm-nic-bios.conf plugins/sshterm/etc/build.conf/sshterm-component.conf"
else
    PLUGIN_CONFS="plugins/kvm/etc/build.conf/kvm-nic-bios.conf"
fi

export OPENQRM_SERVER_BASE_DIR=`dirname $0`
export OPENQRM_SOURCE_DIR=$OPENQRM_SERVER_BASE_DIR
. include/openqrm-functions
. include/openqrm-build-functions

for COMPONENT_CONFIG in `find etc/build.conf/ -type f -name *.conf | grep -v initrd-devices` ; do
	COMPONENT=`basename $COMPONENT_CONFIG`
	COMPONENT=`echo $COMPONENT | sed -e 's/\.conf//g'`
	echo "Checking $COMPONENT"
    openqrm_cache_or_download $COMPONENT $COMPONENT_CONFIG
done
for COMPONENT_CONFIG in $PLUGIN_CONFS; do
	COMPONENT=`basename $COMPONENT_CONFIG`
	COMPONENT=`echo $COMPONENT | sed -e 's/\.conf//g'`
	echo "Checking $COMPONENT"
	openqrm_cache_or_download $COMPONENT $COMPONENT_CONFIG
done





