#!/bin/bash
# this script helps the "make" to call functions 
# from within the Makefile
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=`pwd`/`dirname $0`
OPENQRM_SOURCE_DIR=$OPENQRM_SERVER_BASE_DIR
. $OPENQRM_SOURCE_DIR/etc/openqrm-server.conf
. $OPENQRM_SOURCE_DIR/include/openqrm-functions
. $OPENQRM_SOURCE_DIR/include/openqrm-build-functions
. $OPENQRM_SOURCE_DIR/include/openqrm-package-functions
MAKE_COMMAND=$1

if [ "$MAKE_COMMAND" == "" ]; then
	echo "This script helps the "make" to call functions from within the Makefiles"
	exit 0
fi

$@
