#!/bin/bash
# init script for the openQRM iscsi-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/include/openqrm-plugin-iscsi-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/etc/openqrm-plugin-iscsi-storage.conf



function openqrm_plugin_iscsi_storage_start() {
	echo "Starting the openQRM iscsi-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/iscsi-storage/.running
}


function openqrm_plugin_iscsi_storage_stop() {
	echo "Stopping the openQRM iscsi-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/iscsi-storage/.running
}

function openqrm_plugin_iscsi_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "iscsi-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "iscsi-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM iscsi-storage-plugin"
	openqrm_plugin_iscsi_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD iscsi
	openqrm_server_remove_storagetype $USERNAME $PASSWORD iscsi-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/iscsi-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.iscsi-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.iscsi-menu.html
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/storagetype-capabilities.iscsi-storage-menu.html	
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-iscsi-storage.tgz

	# remove only if lvm-storage is not enabled
	if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep lvm-storage 1>/dev/null 2>&1; then
		if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep netapp-storage 1>/dev/null 2>&1; then
			rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid
			rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm
		fi
	fi
}

function openqrm_plugin_iscsi_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "iscsi-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "iscsi-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM iscsi-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD iscsi "Iscsi-root deployment"
	openqrm_server_add_storagetype $USERNAME $PASSWORD iscsi-storage "Iscsi Storage Server"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/iscsi-storage
	# linking the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/web/boot-service-iscsi-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-iscsi-storage.tgz
	# linking the root mount hook
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/web/root-mount.iscsi-deployment
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/web/root-mount.iscsi-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.iscsi-deployment
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/web/image-deployment-parameter.iscsi-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.iscsi-menu.html
	# linking the storagetype-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-storage/web/storagetype-capabilities.iscsi-storage-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/storagetype-capabilities.iscsi-storage-menu.html

	# copying iscsid to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid ]; then
		cp -f `which iscsid` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying iscsiadm to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm ]; then
		cp -f `which iscsiadm` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_iscsi_storage_start
		;;
	stop)
		openqrm_plugin_iscsi_storage_stop
		;;
	restart)
		openqrm_plugin_iscsi_storage_stop
		sleep 1
		openqrm_plugin_iscsi_storage_start
		;;
	init)
		openqrm_plugin_iscsi_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_iscsi_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




