#!/bin/bash
# this is the boot-service init script for the cloud resources

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/cloud/include/openqrm-plugin-cloud-functions
. $OPENQRM_RESOURCE_PARAMETER_FILE
OPENQRM_SERVER_IP=$resource_openqrmserver
NETWORK_CONF="/tmp/cloud-net.conf"


# do not start on the intitrd
if [ -f /etc/initrd-devices.conf ]; then
	exit 0
fi
# and do not run on the openQRM server itself
if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
	exit 0
fi


function cloud_start() {
	echo "Starting the openQRM cloud-plugin"
	cloud_stop 1>/dev/null 2>&1

	# get the ip-config from the cloud-network-config provider
	rm -f $NETWORK_CONF
	if ! wget -q -O $NETWORK_CONF "http://$resource_openqrmserver/openqrm/action/cloud-conf/cloud-net.conf.$appliance_id"; then
		echo "ERROR: Could not get Cloud network-config from openQRM-server $resource_openqrmserver"
		return 1
	fi
	OPENQRM_INTERFACE=`ifconfig | grep $resource_mac | grep :oq | cut -d':' -f1`
	EXTERNAL_INTERFACES_LIST=`ifconfig -a | grep eth | awk {' print $1 '} | grep -v $OPENQRM_INTERFACE`

	# assign the network conf
	for CONFIG in `cat $NETWORK_CONF`; do
		IP=`echo $CONFIG | cut -d':' -f1`
		SUBNET=`echo $CONFIG | cut -d':' -f2`
		GATEWAY=`echo $CONFIG | cut -d':' -f3`
		DNS1=`echo $CONFIG | cut -d':' -f4`
		DNS2=`echo $CONFIG | cut -d':' -f5`
		DOMAIN=`echo $CONFIG | cut -d':' -f6`
		for INTERFACE in $EXTERNAL_INTERFACES_LIST; do
			# here we set the interface
			ifconfig $INTERFACE $IP netmask $SUBNET up
			# configure the route
			route add default gw $GATEWAY
			# configure /etc/resolv.conf
			> /etc/resolv.conf
			echo "domain $DOMAIN" >> /etc/resolv.conf
			echo "search $DOMAIN" >> /etc/resolv.conf
			echo "nameserver $DNS1" >> /etc/resolv.conf
			echo "nameserver $DNS2" >> /etc/resolv.conf
			# remove interface from the list
			EXTERNAL_INTERFACES_LIST=`echo $EXTERNAL_INTERFACES_LIST | sed -e "s/$INTERFACE//g"`
			export EXTERNAL_INTERFACES_LIST
			break
		done
	done
	rm -f $NETWORK_CONF



}


function cloud_stop() {
	echo "Stopping the openQRM cloud-plugin"
}





case "$1" in
	start)
		cloud_start
		;;
	stop)
		cloud_stop
		;;
	restart)
		cloud_stop
		sleep 1
		cloud_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













