#!/bin/bash
# init script for the openQRM nfs-storage-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/include/openqrm-plugin-nfs-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/etc/openqrm-plugin-nfs-storage.conf



function openqrm_plugin_nfs_storage_start() {
	echo "Starting the openQRM nfs-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nfs-storage/.running
    if [ -x "/etc/init.d/nfs-kernel-server" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d nfs-kernel-server start || exit $?
        else
            /etc/init.d/nfs-kernel-server start || exit $?
        fi
    fi
    if [ -x "/etc/init.d/nfs" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d nfs start || exit $?
        else
            /etc/init.d/nfs start || exit $?
        fi
    fi
    if [ -x "/etc/init.d/nfslock" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d nfslock start || exit $?
        else
            /etc/init.d/nfslock start || exit $?
        fi
    fi
}


function openqrm_plugin_nfs_storage_stop() {
	echo "Stopping the openQRM nfs-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nfs-storage/.running
    if [ -x "/etc/init.d/nfs-kernel-server" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d nfs-kernel-server stop || exit $?
        else
            /etc/init.d/nfs-kernel-server stop || exit $?
        fi
    fi
    if [ -x "/etc/init.d/nfs" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d nfs stop || exit $?
        else
            /etc/init.d/nfs stop || exit $?
        fi
    fi
    if [ -x "/etc/init.d/nfslock" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d nfslock stop || exit $?
        else
            /etc/init.d/nfslock stop || exit $?
        fi
    fi
}

function openqrm_plugin_nfs_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "nfs-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "nfs-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM nfs-storage-plugin"
	openqrm_plugin_nfs_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD nfs-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nfs-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.nfs-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.nfs-deployment.php
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-nfs-storage.tgz
}

function openqrm_plugin_nfs_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "nfs-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "nfs-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM nfs-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD nfs-deployment nfs-deployment "Nfs-root deployment" nfs-storage "NFS Storage"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nfs-storage
	# linking the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/web/boot-service-nfs-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-nfs-storage.tgz
	# linking the root mount hook
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/web/root-mount.nfs-deployment
	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/web/root-mount.nfs-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.nfs-deployment
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/web/image.nfs-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.nfs-deployment.php
    # create storage dir for stat files
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/web/storage
    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-storage/web/storage

}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_nfs_storage_start
		;;
	stop)
		openqrm_plugin_nfs_storage_stop
		;;
	restart)
		openqrm_plugin_nfs_storage_stop
		sleep 1
		openqrm_plugin_nfs_storage_start
		;;
	init)
		openqrm_plugin_nfs_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_nfs_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




