#!/bin/bash
# init script for the openQRM vbox-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/include/openqrm-plugin-vbox-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/etc/openqrm-plugin-vbox.conf

OPENQRM_VM_DIR="/var/lib/vbox/openqrm/"
export OPENQRM_VM_DIR

function openqrm_plugin_vbox_server_start() {
	echo "Starting the openQRM vbox-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vbox/.running
    # start the vm status autostart
    if [ -d "$OPENQRM_VM_DIR" ]; then
        for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart`; do
            VM_NAME=`dirname $VM_CONFIG`
            VM_NAME=`basename $VM_NAME`
            echo "- auto-starting VM $VM_NAME"
            $OPENQRM_VM_DIR/$VM_NAME/$VM_NAME.vbox
        done
    fi
}


function openqrm_plugin_vbox_server_stop() {
	echo "Stopping the openQRM vbox-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vbox/.running
}

function openqrm_plugin_vbox_server_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "vbox: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "vbox: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM vbox-plugin"
	openqrm_plugin_vbox_server_stop
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD vbox
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD vbox-vm
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vbox
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-vbox.tgz
}

function openqrm_plugin_vbox_server_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "vbox: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "vbox: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM vbox-plugin"
	# adding virtualization type	
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD vbox "VirtualBox Host"
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD vbox-vm "VirtualBox VM"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/vbox
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/web/boot-service-vbox.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-vbox.tgz
    chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/bin/*
    # create vbox-stat dir
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/web/vbox-stat
    chmod -R 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/web/vbox-stat

}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_vbox_server_start
		;;
	stop)
		openqrm_plugin_vbox_server_stop
		;;
	restart)
		openqrm_plugin_vbox_server_stop
		sleep 1
		openqrm_plugin_vbox_server_start
		;;
	init)
		openqrm_plugin_vbox_server_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_vbox_server_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




