#!/bin/bash
# this is the boot-service init script for the Vbox-Server hosts
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
# for including the package functions
export OPENQRM_SOURCE_DIR="$OPENQRM_SERVER_BASE_DIR/openqrm/"
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-package-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/include/openqrm-plugin-vbox-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/vbox/etc/openqrm-plugin-vbox.conf
if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
	. $OPENQRM_RESOURCE_PARAMETER_FILE
	OPENQRM_SERVER_IP=$resource_openqrmserver
elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
	openqrm_server_get_config
	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
fi
OPENQRM_VM_DIR="/var/lib/vbox/openqrm/"
export OPENQRM_VM_DIR

# do not start on the intitrd
if [ -f /etc/initrd-devices.conf ]; then
	exit 0
fi


function vbox_start() {
	echo "Starting the openQRM vbox-plugin"
    if ! which VirtualBox 1>/dev/null; then
        exit 0
    fi
   	export FORCE_INSTALL=true
   	openqrm_install_os_dependency screen
    # start the vm status autostart
    if [ -d "$OPENQRM_VM_DIR" ]; then
        for VM_CONFIG in `find $OPENQRM_VM_DIR/* -name autostart`; do
            VM_NAME=`dirname $VM_CONFIG`
            VM_NAME=`basename $VM_NAME`
            echo "- auto-starting VM $VM_NAME"
            $OPENQRM_VM_DIR/$VM_NAME/$VM_NAME.vbox
        done
    fi

}


function vbox_stop() {
	echo "Stopping the openQRM vbox-plugin"

}





case "$1" in
	start)
		vbox_start
		;;
	stop)
		vbox_stop
		;;
	restart)
		vbox_stop
		sleep 1
		vbox_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













