#!/bin/bash
# this is the functions file for the equallogic-storage-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#


# some definitions
DEFAULT_IMAGE_SIZE=5000
EQUALLOGIC_STORAGE_MGMT_LOCK_FILE=/tmp/equallogic-storage-plugin.lock
EQUALLOGIC_STORAGE_MGMT_LOCK_DELAY=5
EQUALLOGIC_STORAGE_MGMT_LOCK_RETRY=100
EQUALLOGIC_STORAGE_MGMT_LOCK_TIMEOUT=500
IMAGE_LUN=1

################ common equallogic-storage functions

# logs for equallogic_storage_storage
function equallogic_storage_storage_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "equallogic-storage plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function equallogic_storage_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $EQUALLOGIC_STORAGE_MGMT_LOCK_FILE` ]; then
		mkdir -p `dirname $EQUALLOGIC_STORAGE_MGMT_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $EQUALLOGIC_STORAGE_MGMT_LOCK_DELAY -r $EQUALLOGIC_STORAGE_MGMT_LOCK_RETRY -l $EQUALLOGIC_STORAGE_MGMT_LOCK_TIMEOUT $EQUALLOGIC_STORAGE_MGMT_LOCK_FILE
				RET=$?
				equallogic_storage_storage_log equallogic_storage_storage_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $EQUALLOGIC_STORAGE_MGMT_LOCK_FILE
				RET=$?
				equallogic_storage_storage_log equallogic_storage_storage_lock "Released the lock"
				return $RET
				;;
		*)
			equallogic_storage_storage_log equallogic_storage_storage_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ equallogic-storage functions














