#!/bin/bash
# this is a hook function for the kernel-creation phase
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

function xen_kernel_hook() {

	local KERNEL_NAME=$1
	local KERNEL_VERSION=$2
	local KERNEL_LOCATION=$3
	local KERNEL_TYPE=$4

	echo "xen-plugin: Running xen_kernel_hook $KERNEL_NAME $KERNEL_VERSION $KERNEL_LOCATION $KERNEL_TYPE"
	echo "xen-plugin: Running xen_kernel_hook $KERNEL_NAME $KERNEL_VERSION $KERNEL_LOCATION $KERNEL_TYPE" | logger
	echo "xen-plugin: basedir = $OPENQRM_SERVER_BASE_DIR" | logger

    if echo $KERNEL_NAME | grep xen 1>/dev/null; then
        if ls $KERNEL_LOCATION/boot/xen*.gz* 1>/dev/null 2>&1; then
            echo "xen-plugin: Found Xen-hypervisor at $KERNEL_LOCATION/boot/"
            echo "xen-plugin: Copying Xen-hypervisor to $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/"
            for XENFILE in `ls $KERNEL_LOCATION/boot/xen*.gz*`; do
                if [ ! -h $XENFILE ]; then
                    cp -f $XENFILE $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/xen-$KERNEL_NAME.gz
                fi
            done
        fi
	fi
	
}