#!/bin/bash
# This function gets called after writing the resource pxe-config file
# It re-writes the config for Xen-boot via mboot.c32

. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions

export XEN_PXE_CONFIG_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/etc/templates/openqrm-pxelinux-xen"
export XEN_VERSION=3.1

function xen_assign_hook() {

	local OPENQRM_RESOURCE_ID=$1
	local OPENQRM_KERNEL_NAME=$2
	local OPENQRM_RESOURCE_PXELINUXCFG_FILE=$3
	local OPENQRM_RESOURCE_MAC=`echo $OPENQRM_RESOURCE_PXELINUXCFG_FILE | sed -e "s/01-//g" | sed -e "s/-/:/g"`

	if echo $OPENQRM_KERNEL_NAME | grep xen 1>/dev/null; then
		echo "xen-plugin: Running assign hook with $OPENQRM_RESOURCE_ID $OPENQRM_KERNEL_NAME $OPENQRM_RESOURCE_PXELINUXCFG_FILE"
		echo "xen-plugin: Running assign hook with $OPENQRM_RESOURCE_ID $OPENQRM_KERNEL_NAME $OPENQRM_RESOURCE_PXELINUXCFG_FILE" | logger
		echo "!!! template $XEN_PXE_CONFIG_TEMPLATE" | logger


		# get more infos about the resource
		openqrm_get_resource_parameter $OPENQRM_RESOURCE_MAC

		cat $XEN_PXE_CONFIG_TEMPLATE |	\
			sed -e "s/@@KERNEL_NAME@@/$OPENQRM_KERNEL_NAME/g" |	\
			sed -e "s/@@XEN_VERSION@@/$XEN_VERSION/g" |	\
			sed -e "s/@@OPENQRM_RESOURCE_ID@@/$OPENQRM_RESOURCE_ID/g" |	\
			sed -e "s/@@OPENQRM_RESOURCE_IP@@/$resource_ip/g" |	\
			sed -e "s/@@OPENQRM_RESOURCE_MAC@@/$OPENQRM_RESOURCE_MAC/g" |	\
			sed -e "s/@@OPENQRM_SERVER_IP_ADDRESS@@/$OPENQRM_SERVER_IP_ADDRESS/g" | \
			sed -e "s/@@OPENQRM_SERVER_SUBNET_MASK@@/$OPENQRM_SERVER_SUBNET_MASK/g" | \
			sed -e "s/@@OPENQRM_SERVER_DEFAULT_GATEWAY@@/$OPENQRM_SERVER_DEFAULT_GATEWAY/g" \
			> $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/$OPENQRM_RESOURCE_PXELINUXCFG_FILE
			chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux.cfg/$OPENQRM_RESOURCE_PXELINUXCFG_FILE
	fi

}

