#!/bin/bash
# this is the functions file for the iscsi-storage-plugin


# iscsi-target config file
IETDCONF=/etc/ietd.conf
# some definitions
DEFAULT_IMAGE_SIZE=5000
ISCSI_MGMT_LOCK_FILE=/var/run/iscsi-storage/iscsi-storage-plugin.lock
ISCSI_MGMT_LOCK_DELAY=5
ISCSI_MGMT_LOCK_RETRY=100
ISCSI_MGMT_LOCK_TIMEOUT=500
ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY="/target"
ISCSI_TARGET_URL=http://iscsitarget.sourceforge.net/

################ common iscsi-storage functions

# logs for iscsi_storage
function iscsi_storage_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "iscsi-storage plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function iscsi_storage_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $ISCSI_MGMT_LOCK_FILE` ]; then
		mkdir -p `dirname $ISCSI_MGMT_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $ISCSI_MGMT_LOCK_DELAY -r $ISCSI_MGMT_LOCK_RETRY -l $ISCSI_MGMT_LOCK_TIMEOUT $ISCSI_MGMT_LOCK_FILE
				RET=$?
				iscsi_storage_log iscsi_storage_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $ISCSI_MGMT_LOCK_FILE
				RET=$?
				iscsi_storage_log iscsi_storage_lock "Released the lock"
				return $RET
				;;
		*)
			iscsi_storage_log iscsi_storage_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ iscsi-storage functions




function check_iscsi_target() {
	# iscsi-target installed ?
	if ! ls $IETDCONF 1>/dev/null; then
		echo "ERROR: Iscsi Enterprise Target not installed !"
		echo "ERROR: For managing Iscsi filesystem-images please download and install from"
		echo "       $ISCSI_TARGET_URL"
		iscsi_storage_log iscsi-storage-functions "ERROR: Iscsi Enterprise Target not installed !"
		iscsi_storage_lock release
		return 1
	fi			
}



function manage_iscsi() {

	if ! check_iscsi_target; then
		return
	fi
	case "$1" in
		add)
			IMAGE_PASS=$3
			# create the image file
			if [ "$2" != "snap" ]; then
				dd if=/dev/zero of=$ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME bs=1M seek=$ISCSI_IMAGE_SIZE count=1
				# create fs, currently static all ext3
				mkfs.ext3 -F $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME
			fi
			IMAGE_LUN=1
			echo "Target $ISCSI_IMAGE_NAME" >> $IETDCONF
			echo "	IncomingUser $ISCSI_IMAGE_NAME $IMAGE_PASS" >> $IETDCONF
			echo "	Lun $IMAGE_LUN Path=$ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME,Type=fileio" >> $IETDCONF
			if [ -x /etc/init.d/iscsi-target ]; then
				/etc/init.d/iscsi-target stop
				nohup /etc/init.d/iscsi-target start
			elif [ -x /etc/init.d/iscsitarget ]; then
				/etc/init.d/iscsitarget stop
				nohup /etc/init.d/iscsitarget start
			else
				echo "ERROR: Coud not find the iscsi-target init script !" | logger
			fi
			;;
		auth)
			IMAGE_PASS=$2
			IMAGE_AUTHNAME=`echo $ISCSI_IMAGE_ROOTDEVICE | cut -d'/' -f3`
			sed -i -e "s#IncomingUser $IMAGE_AUTHNAME .*#IncomingUser $IMAGE_AUTHNAME $IMAGE_PASS#g" $IETDCONF
			sed -i '/^$/d' $IETDCONF
			if [ -x /etc/init.d/iscsi-target ]; then
				/etc/init.d/iscsi-target stop
				nohup /etc/init.d/iscsi-target start
			elif [ -x /etc/init.d/iscsitarget ]; then
				/etc/init.d/iscsitarget stop
				nohup /etc/init.d/iscsitarget start
			else
				echo "ERROR: Coud not find the iscsi-target init script !" | logger
			fi
			;;
		remove)
			sed -i -e "s#.*$ISCSI_IMAGE_NAME.*##g" $IETDCONF
			sed -i '/^$/d' $IETDCONF
			if [ -x /etc/init.d/iscsi-target ]; then
				/etc/init.d/iscsi-target stop
				nohup /etc/init.d/iscsi-target start
			elif [ -x /etc/init.d/iscsitarget ]; then
				/etc/init.d/iscsitarget stop
				nohup /etc/init.d/iscsitarget start
			else
				echo "ERROR: Coud not find the iscsi-target init script !" | logger
			fi
			rm -f $ISCSI_STORAGE_SERVER_IMAGE_DIRECTORY/$ISCSI_IMAGE_NAME
			;;
	esac
}
















