#!/bin/bash
# this is the functions file for the nfs-storage-plugin

# some definitions
DEFAULT_IMAGE_SIZE=5000
NFS_MGMT_LOCK_FILE=/var/run/nfs-storage/nfs-storage-plugin.lock
NFS_MGMT_LOCK_DELAY=5
NFS_MGMT_LOCK_RETRY=100
NFS_MGMT_LOCK_TIMEOUT=500
NFS_STORAGE_SERVER_IMAGE_DIRECTORY="/exports"

################ common nfs-storage functions

# logs for nfs_storage
function nfs_storage_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "nfs-storage plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function nfs_storage_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $NFS_MGMT_LOCK_FILE` ]; then
		mkdir -p `dirname $NFS_MGMT_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $NFS_MGMT_LOCK_DELAY -r $NFS_MGMT_LOCK_RETRY -l $NFS_MGMT_LOCK_TIMEOUT $NFS_MGMT_LOCK_FILE
				RET=$?
				nfs_storage_log nfs_storage_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $NFS_MGMT_LOCK_FILE
				RET=$?
				nfs_storage_log nfs_storage_lock "Released the lock"
				return $RET
				;;
		*)
			nfs_storage_log nfs_storage_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ nfs-storage functions


function manage_nfs() {
	case "$1" in
		add)
			mkdir -p $NFS_STORAGE_SERVER_IMAGE_DIRECTORY/$NFS_IMAGE_NAME
			echo "$NFS_STORAGE_SERVER_IMAGE_DIRECTORY/$NFS_IMAGE_NAME	*(rw,insecure,no_root_squash,async)" >> /etc/exports
			if [ -x /etc/init.d/nfs ]; then
				/etc/init.d/nfs reload
			elif [ -x /etc/init.d/nfs-kernel-server ]; then
				/etc/init.d/nfs-kernel-server reload
			else
				echo "WARNING: Could not find nfs-server init script !"
			fi
			;;
		remove)
			cat /etc/exports | sed -e "s#^$NFS_STORAGE_SERVER_IMAGE_DIRECTORY/$NFS_IMAGE_NAME.*##g" > /tmp/exports.tmp-update
			/bin/mv -f /tmp/exports.tmp-update /etc/exports
			if [ -x /etc/init.d/nfs ]; then
				/etc/init.d/nfs reload
			elif [ -x /etc/init.d/nfs-kernel-server ]; then
				/etc/init.d/nfs-kernel-server reload
			else
				echo "WARNING: Could not find nfs-server init script !"
			fi
			rm -rf $NFS_STORAGE_SERVER_IMAGE_DIRECTORY/$NFS_IMAGE_NAME/*
			rmdir $NFS_STORAGE_SERVER_IMAGE_DIRECTORY/$NFS_IMAGE_NAME
			;;
	esac
}



