#!/bin/bash
# init script for the openQRM aoe-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/include/openqrm-plugin-aoe-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/etc/openqrm-plugin-aoe-storage.conf


function openqrm_plugin_aoe_storage_start() {
	echo "Starting the openQRM aoe-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage/.running
	if [ -x /etc/init.d/vblade ]; then
	/etc/init.d/vblade start; else
	log_daemon_msg "Starting vblade deaemons" "vblade"
   if [ `grep -vc '^#\|^$' /etc/$prog.conf` ]
   then
        grep -v '^#' /etc/$prog.conf | sed -e 's/       / /g' -e 's/  / /g' | while read line
        do
                 start_vblade $line
        done
   else
        echo -n "empty $prog.conf?"
        echo
   fi
   fi
}


function openqrm_plugin_aoe_storage_stop() {
	echo "Stopping the openQRM aoe-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage/.running
	if [ -x /etc/init.d/vblade ]; then
	/etc/init.d/vblade start; else
	log_daemon_msg "Stopping vblade daemons" "vblade"
   log_progress_msg "vblade"
   for pidfile in `ls /var/run/$prog/*.pid`
   do
        kill -9 `cat $pidfile`
        rm -f $pidfile
  done
  echo
	fi
}

function openqrm_plugin_aoe_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "aoe-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "aoe-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM aoe-storage-plugin"
	openqrm_plugin_aoe_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD aoe-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.aoe-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-aoe-storage.tgz
	# remove only if lvm-storage is not enabled
	if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep lvm-storage 1>/dev/null 2>&1; then
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-interfaces
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-discover
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-stat
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs
		rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf
	fi
}

function openqrm_plugin_aoe_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "aoe-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "aoe-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM aoe-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD aoe-deployment aoe-deployment "Aoe-root deployment" aoe-storage "Aoe/Coraid Storage"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage
	# linking the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/boot-service-aoe-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-aoe-storage.tgz
	# linking the root mount hook
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/root-mount.aoe-deployment
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/root-mount.aoe-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-deployment
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/image.aoe-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.aoe-deployment

	# copying aoe-interfaces to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-interfaces ]; then
		cp -f `which aoe-interfaces` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying aoe-discover to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-discover ]; then
		cp -f `which aoe-discover` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying aoe-stat to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-stat ]; then
		cp -f `which aoe-stat` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying aoe-mkdevs to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs ]; then
		cp -f `which aoe-mkdevs` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
		# remove the axwwww from the ps cmd in aoe-mkdevs
		sed -i -e "s/axwwww//g" $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs
	fi
	# copying aoe-mkshelf to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf ]; then
		cp -f `which aoe-mkshelf` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
		# remove the axwwww from the ps cmd in aoe-mkshelf
		sed -i -e "s/axwwww//g" $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf
	fi
	
}

USER=$2
PASS=$3

### additions for autostarting aoe-blades
. /lib/lsb/init-functions

RETVAL=0
prog=vblade

start_vblade() {
   ALLOWMACS=""
   [ -n "$5" ] && ALLOWMACS="-m $5"
   ID="$1-e$2.$3"
   PID_FILE=/var/run/$prog/${ID}.pid
   $prog $ALLOWMACS $2 $3 $1 $4 >> /var/log/$prog.log 2>&1 &
   pid=$i
   echo $pid > $PID_FILE
   echo -n $"$4 (e$2.$3@$1) [pid $pid]"
   [ "$RETVAL" = 0 ] && log_end_msg 0 || log_end_msg 1
   echo
}

case "$1" in
	start)
		openqrm_plugin_aoe_storage_start
		;;
	stop)
		openqrm_plugin_aoe_storage_stop
		;;
	restart)
		openqrm_plugin_aoe_storage_stop
		sleep 1
		openqrm_plugin_aoe_storage_start
		;;
	init)
		openqrm_plugin_aoe_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_aoe_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?
