#!/bin/bash
# init script for the openQRM aoe-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/include/openqrm-plugin-aoe-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/etc/openqrm-plugin-aoe-storage.conf


function openqrm_plugin_aoe_storage_start() {
	echo "Starting the openQRM aoe-storage-plugin"
}


function openqrm_plugin_aoe_storage_stop() {
	echo "Stopping the openQRM aoe-storage-plugin"
}

function openqrm_plugin_aoe_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "aoe-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "aoe-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM aoe-storage-plugin"
	openqrm_plugin_aoe_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD aoe
	openqrm_server_remove_storagetype $USERNAME $PASSWORD aoe-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.aoe-menu.html
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-interfaces
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-discover
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-stat
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkdevs
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/aoe-mkshelf
}

function openqrm_plugin_aoe_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "aoe-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "aoe-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM aoe-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD aoe "Aoe-root deployment"
	openqrm_server_add_storagetype $USERNAME $PASSWORD aoe-storage "Aoe/Coraid Storage Server"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/aoe-storage
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/root-mount.aoe-storage
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/root-mount.aoe-storage $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.aoe-storage
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/aoe-storage/web/image-deployment-parameter.aoe-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.aoe-menu.html
	# copying aoe-interfaces to boot-service dir
	cp -f `which aoe-interfaces` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-discover to boot-service dir
	cp -f `which aoe-discover` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-stat to boot-service dir
	cp -f `which aoe-stat` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-mkdevs to boot-service dir
	cp -f `which aoe-mkdevs` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying aoe-mkshelf to boot-service dir
	cp -f `which aoe-mkshelf` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_aoe_storage_start
		;;
	stop)
		openqrm_plugin_aoe_storage_stop
		;;
	restart)
		openqrm_plugin_aoe_storage_stop
		sleep 1
		openqrm_plugin_aoe_storage_start
		;;
	init)
		openqrm_plugin_aoe_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_aoe_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




