#!/bin/bash
# this is the functions file for the dhcpd-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_DEFAULT_DOMAIN="openqrm"
OPENQRM_PLUGIN_DHCPD_CONF_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/etc/templates/openqrm-plugin-dhcpd-configuration.template"
OPENQRM_PLUGIN_DHCPD_CONF="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/etc/dhcpd.conf"
OPENQRM_PLUGIN_DHCPD_LEASE_DIR="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/var/state/dhcp"
DHCPD_LOCK_FILE=/var/run/dhcpd/dhcpd-plugin.lock
DHCPD_LOCK_DELAY=5
DHCPD_LOCK_RETRY=100
DHCPD_LOCK_TIMEOUT=500


# logs for dhcpd
function dhcpd_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "dhcpd plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function dhcpd_lock() {
	local COMMAND=$1
	local RET=1
	if [ ! -d `dirname $DHCPD_LOCK_FILE` ]; then
		mkdir -p `dirname $DHCPD_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $DHCPD_LOCK_DELAY -r $DHCPD_LOCK_RETRY -l $DHCPD_LOCK_TIMEOUT $DHCPD_LOCK_FILE
				RET=$?
				dhcpd_log dhcpd_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $DHCPD_LOCK_FILE
				RET=$?
				dhcpd_log dhcpd_lock "Released the lock"
				return $RET
				;;
		*)
			dhcpd_log dhcpd_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}






#
# get the network address for a ip and a subnet mask
#
# perl script adapted from ipcalc 0.41 (http://jodies.de/ipcalc), written by
# Krischan Jodies
#
# $1:  ip address
# $2:  subnet mask
# out: network address
#
function openqrm_plugin_dhcpd_get_netaddr() {
	perl - $1 $2 <<'EOF'
print ntoa(argton($ARGV[1]) & argton($ARGV[0]))."\n";

# input argument to number
sub argton
{
    my $arg = shift;
    my $i = 24;
    my $n = 0;

    if ($arg =~ /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/) {
        my @decimals = ($1,$2,$3,$4);
        foreach (@decimals) {
            if ($_ > 255 || $_ < 0) {
                return -1;
            }
            $n += $_ << $i;
            $i -= 8;
        }
        return $n;
    } else {
        return -1;
    }
}

# number to dotted decimal address
sub ntoa
{
    return join ".",unpack("CCCC",pack("N",shift));
}
EOF
}


