#!/bin/bash
# this is the functions file for the dhcpd-plugin

OPENQRM_SERVER_DEFAULT_DOMAIN="openqrm"
OPENQRM_PLUGIN_DHCPD_CONF_TEMPLATE="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/etc/templates/openqrm-plugin-dhcpd-configuration.template"
OPENQRM_PLUGIN_DHCPD_CONF="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/etc/dhcpd.conf"
OPENQRM_PLUGIN_DHCPD_LEASE_DIR="$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/var/state/dhcp"


#
# get the network address for a ip and a subnet mask
#
# perl script adapted from ipcalc 0.41 (http://jodies.de/ipcalc), written by
# Krischan Jodies
#
# $1:  ip address
# $2:  subnet mask
# out: network address
#
function openqrm_plugin_dhcpd_get_netaddr() {
	perl - $1 $2 <<'EOF'
print ntoa(argton($ARGV[1]) & argton($ARGV[0]))."\n";

# input argument to number
sub argton
{
    my $arg = shift;
    my $i = 24;
    my $n = 0;

    if ($arg =~ /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/) {
        my @decimals = ($1,$2,$3,$4);
        foreach (@decimals) {
            if ($_ > 255 || $_ < 0) {
                return -1;
            }
            $n += $_ << $i;
            $i -= 8;
        }
        return $n;
    } else {
        return -1;
    }
}

# number to dotted decimal address
sub ntoa
{
    return join ".",unpack("CCCC",pack("N",shift));
}
EOF
}
