#!/bin/bash
# this is the boot-service init script for the puppet resources

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
# for including the package functions
export OPENQRM_SOURCE_DIR="$OPENQRM_SERVER_BASE_DIR/openqrm/"
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-package-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/puppet/include/openqrm-plugin-puppet-functions
. $OPENQRM_RESOURCE_PARAMETER_FILE
OPENQRM_SERVER_IP=$resource_openqrmserver

# do not run on idle resources
if [ "$resource_image" == "idle" ]; then
	exit 0
fi
# set the hostname :)
hostname $appliance_name


function puppet_start() {
	echo "Starting the openQRM puppet-plugin"
	puppet_stop 1>/dev/null 2>&1
	export FORCE_INSTALL=true
	openqrm_install_os_dependency puppet
}


function puppet_stop() {
	echo "Stopping the openQRM puppet-plugin"
}





case "$1" in
	start)
		puppet_start
		;;
	stop)
		puppet_stop
		;;
	restart)
		puppet_stop
		sleep 1
		puppet_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













