#!/bin/bash
# init script for the openQRM equallogic-storage-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/include/openqrm-plugin-equallogic-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/etc/openqrm-plugin-equallogic-storage.conf
# get the ip config
openqrm_server_get_config
export resource_openqrmserver=$OPENQRM_SERVER_IP_ADDRESS
export LANG=C
# define wget to use with https
if [ "$OPENQRM_WEB_PROTOCOL" == "https" ]; then
    WGET_NO_CERT_CHECK="--no-check-certificate"
fi

function openqrm_plugin_equallogic_storage_start() {
	openqrm_plugin_equallogic_storage_stop 1>/dev/null 2>&1
	echo "Starting the openQRM equallogic-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/equallogic-storage/.running
}


function openqrm_plugin_equallogic_storage_stop() {
	echo "Stopping the openQRM equallogic-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/equallogic-storage/.running
}

function openqrm_plugin_equallogic_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "equallogic-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "equallogic-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM equallogic-storage-plugin"
	openqrm_plugin_equallogic_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD equallogic
	# removing the eq-server table
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/equallogic-storage/equallogic-storage-action.php?equallogic_storage_command=uninstall"; then
		equallogic_storage_storage_log uninstall "ERROR: Could not drop the Equallogig-Storage plugin tables in the database!"
	fi

	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/equallogic-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.equallogic
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.equallogic.php
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-equallogic-storage.tgz
    rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/eq-resize.default.tgz

	# remove only if lvm-storage is not enabled
	if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep lvm-storage 1>/dev/null 2>&1; then
		if ! ls $OPENQRM_SERVER_BASE_DIR/openqrm/web/base/plugins | grep netapp-storage 1>/dev/null 2>&1; then
			rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid
			rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm
		fi
	fi
}

function openqrm_plugin_equallogic_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "equallogic-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "equallogic-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM equallogic-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD equallogic equallogic "EqualLogic-root deployment" equallogic-storage "EqualLogic Storage"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/equallogic-storage
	# linking the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web/boot-service-equallogic-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-equallogic-storage.tgz
	# linking the root mount hook
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web/root-mount.equallogic
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web/root-mount.equallogic $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.equallogic
	# linking the root mount action hook
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web/root-mount.equallogic.action.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.equallogic.action.php
	# linking the default image-parameters
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web/image.equallogic.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.equallogic.php
	# copying iscsid to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid ]; then
		cp -f `which iscsid` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi
	# copying iscsiadm to boot-service dir
	if [ ! -x $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm ]; then
		cp -f `which iscsiadm` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	fi

    # resize components for the default kernel
    RESIZE_TMP_DIR=`mktemp -d /tmp/XXXXXXXXXX` || exit 1
    mkdir -p $RESIZE_TMP_DIR/sbin $RESIZE_TMP_DIR/lib
    if [ -x "/sbin/e2fsck" ]; then
        cp -a /sbin/e2fsck $RESIZE_TMP_DIR/sbin/
        RESIZE_COMPONENTS=true
    fi
    if [ -x "/sbin/resize2fs" ]; then
        cp -a /sbin/resize2fs $RESIZE_TMP_DIR/sbin/
        RESIZE_COMPONENTS=true
    fi
    if [ "$RESIZE_COMPONENTS" == "true" ]; then
        THIS_DIR=`pwd`
        # copy libs
        cp -a $KERNEL_LOCATION/lib/libe2p.* $RESIZE_TMP_DIR/lib/
        cp -a $KERNEL_LOCATION/lib/libext2fs.* $RESIZE_TMP_DIR/lib/
        cd $RESIZE_TMP_DIR/
        rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/eq-resize.default.tgz
        tar -czf $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/eq-resize.default.tgz *
        cd $THIS_DIR
    fi
    rm -rf $RESIZE_TMP_DIR/sbin $RESIZE_TMP_DIR/lib
    rmdir $RESIZE_TMP_DIR

	# creating the tables
	if ! wget -q $WGET_NO_CERT_CHECK -O /dev/null --http-user=$USERNAME --http-password=$PASSWORD "$OPENQRM_WEB_PROTOCOL://$resource_openqrmserver/openqrm/base/plugins/equallogic-storage/equallogic-storage-action.php?equallogic_storage_command=init"; then
		equallogic_storage_storage_log uninstall "ERROR: Could not initialyze the EqualLogic-Storage-plugin tables in the database!"
        exit 1
	fi
    # create storage dir for stat files
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web/storage
    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/equallogic-storage/web/storage
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_equallogic_storage_start
		;;
	stop)
		openqrm_plugin_equallogic_storage_stop
		;;
	restart)
		openqrm_plugin_equallogic_storage_stop
		sleep 1
		openqrm_plugin_equallogic_storage_start
		;;
	init)
		openqrm_plugin_equallogic_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_equallogic_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




