#!/bin/bash -x
########################## build functions ##########################

# in the stage these function are used the files may be not installed yet

if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
	echo "ERROR: Please export OPENQRM_SERVER_BASE_DIR before sourcing $0"
	exit 1
fi
if [ "$OPENQRM_SOURCE_DIR" == "" ]; then
	echo "ERROR: Please export OPENQRM_SOURCE_DIR before sourcing $0"
	exit 1
fi
# source the openqrm-functions file for more features
. $OPENQRM_SOURCE_DIR/include/openqrm-functions
# source the openqrm-server.conf which resets the basedir again
. $OPENQRM_SOURCE_DIR/etc/openqrm-server.conf

OPENQRM_BUILD_DISTRIBUTION=`openqrm_get_distro`
if [ "$OPENQRM_BUILD_DISTRIBUTION" == "fc7" ] || [ "$OPENQRM_BUILD_DISTRIBUTION" == "fc8" ] ; then
	# portmap was replaced with rpcbind on fc > 7
	OPENQRM_INITRD_COMPONENTS="/bin/bash /sbin/rpcbind /usr/bin/rsync /sbin/modprobe /sbin/depmod /sbin/insmod /sbin/lsmod /sbin/mke2fs /sbin/sfdisk"
else
	OPENQRM_INITRD_COMPONENTS="/bin/bash /sbin/portmap /usr/bin/rsync /sbin/modprobe /sbin/depmod /sbin/insmod /sbin/lsmod /sbin/mke2fs /sbin/sfdisk"
fi
OPENQRM_INITRD_DIRECTORIES="bin etc etc/rc.d/init.d etc/sysconfig etc/X11 lib lib/modules lib/i686 loopfs mnt old_root proc sys sysroot usr usr/lib usr/bin usr/sbin var var/lock var/lock/subsys var/log var/run /var/lib /var/lib/nfs /var/lib/nfs/statd"



# function displaying the library files (not links) a binary depends on
# -> this is generic
function openqrm_build_find_libs() {
	BINARY=$1
	for LIBRARY in `ldd $BINARY | awk {' print $3 '}`; do
		REAL_LIBRARYFILE=`readlink $LIBRARY`
		if [ "$REAL_LIBRARYFILE" == "" ]; then
			REAL_LIBRARYFILE=`basename $LIBRARY`
		fi
		FULL_PATH_TO_LIBRARY=`dirname $LIBRARY`
		if [ "$FULL_PATH_TO_LIBRARY" != "." ]; then
			echo $FULL_PATH_TO_LIBRARY/$REAL_LIBRARYFILE
		fi
	done



}



# function to check the requirements for the compile phase
# -> this is for "make all" / comilation phase
function openqrm_check_build_requirements() {
	echo "Checking requirements for the compilation phase"
	# check which command to use for checking the requirements
	if [ -f /etc/debian_version ]; then
		OPENQRM_PACKAGE_TYPE=deb
		OPENQRM_REQUIREMENTS_CHECK_COMMAND="dpkg -L"
		OPENQRM_PACKAGE_INSTALL_CMD="apt-get install"
	elif [ -f /etc/redhat-release ]; then
		OPENQRM_PACKAGE_TYPE=rpm
		OPENQRM_REQUIREMENTS_CHECK_COMMAND="rpm -qs"
		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
	elif [ -f /etc/SuSE-release ]; then
		OPENQRM_PACKAGE_TYPE=rpm
		OPENQRM_REQUIREMENTS_CHECK_COMMAND="rpm -qs"
		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
	else
		echo "NOTICE: Could not find out which compile-requirements to use"
		echo "        Please make sure to have all needed components installed!"
		sleep 4
		echo "... Continuing anyway"
		return 0
	fi

	echo "openqrm-server requires : $OPENQRM_SERVER_BUILD_REQUIREMENTS"
	for DEP in `echo $OPENQRM_SERVER_BUILD_REQUIREMENTS | sed -e "s/,//g"`; do
		if $OPENQRM_REQUIREMENTS_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
			echo "-> found $DEP installed"
		else
			echo "NOTICE: Trying to automatically install $DEP ..."
			if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
				echo "ERROR: $DEP could not be installed. Please install manually to continue"
				return 1
			fi
		fi
	done


	# check if the build tmp directory is writable
	if [ ! -d "$OPENQRM_BUILD_TMP_DIR" ]; then
		if ! mkdir -p "$OPENQRM_BUILD_TMP_DIR"; then
			echo "ERROR: $OPENQRM_BUILD_TMP_DIR could not be created by user `whoami`."
			return 1;
		fi	
	elif [ ! -w "$OPENQRM_BUILD_TMP_DIR" -o ! -x "$OPENQRM_BUILD_TMP_DIR" ]; then
		echo "ERROR: $OPENQRM_BUILD_TMP_DIR must exist and be writable by user `whoami`."
		return 1;
	fi



	# get a list of plugins for checking their requirements
	OPENQRM_PACKAGE_COMPONENT_LIST=`ls $OPENQRM_SOURCE_DIR/plugins | grep -v Makefile | grep -v CVS`
	for OPENQRM_PLUGIN in $OPENQRM_PACKAGE_COMPONENT_LIST; do
		. $OPENQRM_SOURCE_DIR/plugins/$OPENQRM_PLUGIN/etc/openqrm-plugin-$OPENQRM_PLUGIN"".conf
		echo "openqrm-plugin-$OPENQRM_PLUGIN requires : `echo $OPENQRM_PLUGIN_BUILD_REQUIREMENTS`"
		for DEP in `echo $OPENQRM_PLUGIN_BUILD_REQUIREMENTS | sed -e "s/,//g"`; do
			if $OPENQRM_REQUIREMENTS_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
				echo "-> found $DEP installed"
			else
				echo "NOTICE: Trying to automatically install $DEP ..."
				if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
					echo "ERROR: $DEP could not be installed. Please install manually to continue"
					return 1
				fi
			fi
		done
	done
	echo "Checking for required components to compile openQRM finished successfully"

}


# function to download+cache source packages in the package-dir
# -> this is for "make all" / comilation phase
function openqrm_cache_or_download() {
	# 1 param: 		component name
	# 2 param:		component build config file
	OPENQRM_SOURCE_COMPONENT_NAME=$1
	OPENQRM_SOURCE_COMPONENT_BUILD_CONFIG=$2
	if [ "$OPENQRM_SOURCE_COMPONENT_BUILD_CONFIG" == "" ]; then
		. $OPENQRM_SOURCE_DIR/etc/build.conf/$OPENQRM_SOURCE_COMPONENT_NAME.conf
	else
		. $OPENQRM_SOURCE_COMPONENT_BUILD_CONFIG
	fi
	OPENQRM_SOURCE_COMPONENT_FILE=`basename $OPENQRM_SOURCE_DOWNLOAD`
	CURRENT_DIR=`pwd`
	if [ -f $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/$OPENQRM_SOURCE_COMPONENT_FILE ]; then
		echo "-> found component $OPENQRM_SOURCE_COMPONENT_NAME ($OPENQRM_SOURCE_COMPONENT_FILE) already downloaded"
	else
		mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/
		cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/
		if ! wget $OPENQRM_SOURCE_DOWNLOAD; then
			echo "ERROR: Could not download $OPENQRM_SOURCE_COMPONENT_NAME from $OPENQRM_SOURCE_DOWNLOAD"
			echo "       Please put $OPENQRM_SOURCE_COMPONENT_FILE in $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/ and try again."
			exit 1
		fi
	fi
	cp -f $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/source/$OPENQRM_SOURCE_COMPONENT_FILE $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/
	cd $CURRENT_DIR
}



#function to compile a component from the source
# -> this is for "make all" / compilation phase
function openqrm_compile_from_source() {
	# 1 param: 		component name
	# 2 param:		component build config file
	# optional variables :
	# OPENQRM_CONFIGURE		command to use for configure (default "./configure" if exists)
	# OPENQRM_PRE_MAKE		commands to run before make
	# OPENQRM_POST_MAKE		commands to run after make
	OPENQRM_SOURCE_COMPONENT_NAME=$1
	OPENQRM_SOURCE_COMPONENT_BUILD_CONFIG=$2
	if [ "$OPENQRM_SOURCE_COMPONENT_BUILD_CONFIG" == "" ]; then
		. $OPENQRM_SOURCE_DIR/etc/build.conf/$OPENQRM_SOURCE_COMPONENT_NAME.conf
	else
		. $OPENQRM_SOURCE_COMPONENT_BUILD_CONFIG
	fi
	OPENQRM_SOURCE_COMPONENT_FILE=`basename $OPENQRM_SOURCE_DOWNLOAD`
	CURRENT_DIR=`pwd`
	# check if it is already compiled
	if [ ! -f $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/$OPENQRM_SOURCE_BINARY_RESULT ]; then
		# nope, then we have to build it
		# unpack
		cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/$OPENQRM_SOURCE_COMPONENT_NAME/
		OPENQRM_SOURCE_COMPONENT_FILE_TYPE=`echo $OPENQRM_SOURCE_COMPONENT_FILE | sed -e "s/.*\.//g"`
		if [ "$OPENQRM_SOURCE_COMPONENT_FILE_TYPE" == "bz2" ]; then
			tar -xjf $OPENQRM_SOURCE_COMPONENT_FILE
		else
			tar -xzf $OPENQRM_SOURCE_COMPONENT_FILE
		fi
		rm -f $OPENQRM_SOURCE_COMPONENT_FILE
		cd $OPENQRM_SOURCE_COMPONENT_NAME-$OPENQRM_SOURCE_VERSION

		# configure
		if [ "$OPENQRM_CONFIGURE" != "" ]; then
			$OPENQRM_CONFIGURE
		elif [ -f ./configure ]; then
			chmod +x ./configure && ./configure
		fi

		# pre-make
		eval $OPENQRM_PRE_MAKE

		# make
		make $OPENQRM_MAKE_TARGET
		# we do not run make install, if needed pls run it in post-make

		# post-make
		eval $OPENQRM_POST_MAKE

		unset OPENQRM_CONFIGURE OPENQRM_PRE_MAKE OPENQRM_POST_MAKE
		cd $CURRENT_DIR
	else
		echo "-> Found $OPENQRM_SOURCE_BINARY_RESULT already in the build-cache"
		echo "-> Skipping compilation, taking the ready build component from the cache"
	fi
}



# function to create the default initrd-template during the compile stage
# -> this is for "make install" / installation phase
function openqrm_create_default_initrd_template() {

	CURRENT_DIR=`pwd`
	OPENQRM_SOURCE_DIR_FULL_PATH=`cd $OPENQRM_SOURCE_DIR && pwd && cd $CURRENT_DIR`
	echo "Creating the default initrd-template"
	# getting + compiling busybox
	. $OPENQRM_SOURCE_DIR/etc/build.conf/busybox.conf
	openqrm_cache_or_download busybox
	OPENQRM_SOURCE_COMPONENT_BUILD_DIR=$OPENQRM_BUILD_TMP_DIR/openqrm-build/busybox/busybox-$OPENQRM_SOURCE_VERSION/
	export OPENQRM_PRE_MAKE="cp $OPENQRM_SOURCE_DIR_FULL_PATH/etc/build.conf/busybox.configuration $OPENQRM_SOURCE_COMPONENT_BUILD_DIR/.config && make oldconfig"
	export OPENQRM_POST_MAKE="make install"
	openqrm_compile_from_source busybox
	# getting hwdata
	openqrm_cache_or_download hwdata-knoppix
	export DESTDIR=$OPENQRM_BUILD_TMP_DIR/openqrm-build/hwdata-knoppix/hwdata-install
	export OPENQRM_POST_MAKE="make install"
	openqrm_compile_from_source hwdata-knoppix
	. $OPENQRM_SOURCE_DIR/etc/build.conf/hwdata-knoppix.conf
	cp -a $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwdata-knoppix/hwdata-knoppix-$OPENQRM_SOURCE_VERSION/debian/pcitable-knoppix $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwdata-knoppix/hwdata-install/usr/share/hwdata/pcitable
	# kudzu
	openqrm_cache_or_download kudzu-knoppix
	export OPENQRM_MAKE_TARGET=libkudzu.a
	openqrm_compile_from_source kudzu-knoppix
	# hwsetup
	openqrm_cache_or_download hwsetup
	# we need some more includes/libs as provided in the hwsetup Makefile
	# so we compile it manually
	. $OPENQRM_SOURCE_DIR/etc/build.conf/kudzu-knoppix.conf
	OPENQRM_SOURCE_KUDZU_DIR="$OPENQRM_BUILD_TMP_DIR/openqrm-build/kudzu-knoppix/kudzu-knoppix-$OPENQRM_SOURCE_VERSION/"
	. $OPENQRM_SOURCE_DIR/etc/build.conf/hwsetup.conf
	
	OPENQRM_SOURCE_HWSETUP_FILE=`basename $OPENQRM_SOURCE_DOWNLOAD`
	OPENQRM_SOURCE_HWSETUP_DIR="$OPENQRM_BUILD_TMP_DIR/openqrm-build/hwsetup/hwsetup-$OPENQRM_SOURCE_VERSION/"
	tar -C $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwsetup/ -xzf $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwsetup/$OPENQRM_SOURCE_HWSETUP_FILE
	cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwsetup/hwsetup-$OPENQRM_SOURCE_VERSION
	cc -I$OPENQRM_SOURCE_KUDZU_DIR -DBLACKLIST -Wall -fPIC -O2 -s -o hwsetup hwsetup.c -L$OPENQRM_SOURCE_KUDZU_DIR -lkudzu -lpci -lz
	cd $CURRENT_DIR

	# create the initroot
	mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot
	cp -aR $OPENQRM_SOURCE_COMPONENT_BUILD_DIR/_install/* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/

	# create lib dir + copy ld-linux
	mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib
	cp -a /lib/ld-* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/

	# add the libs busybox depends on
	for LIB in `openqrm_build_find_libs $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/bin/busybox`; do
		LIB=`echo $LIB | cut -d'-' -f1 | cut -d'.' -f1`
		if [ "$LIB" != "/lib/" ]; then
			cp -a $LIB""* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
		fi
	done
	# add some more utils + their libs
	for UTIL in $OPENQRM_INITRD_COMPONENTS; do
		cp -a $UTIL $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/bin
		echo "Adding $UTIL to default initrd-template"
		for LIB in `openqrm_build_find_libs $UTIL`; do
			LIB=`echo $LIB | cut -d'-' -f1 | cut -d'.' -f1`
			if [ "$LIB" != "/lib/" ]; then
				cp -a $LIB""* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
			fi
		done
	done
	# fix reboot for the initrd -> reboot -f (it's simply faster)
	rm -f $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/sbin/reboot
	cat >> $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/sbin/reboot << EOF
#!/bin/bash
/bin/busybox reboot -f
EOF
	chmod +x $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/sbin/reboot
	# creating initrd directories
	for DIR in $OPENQRM_INITRD_DIRECTORIES; do
		mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/$DIR
	done
	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/rmtab 
	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/xtab  
	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/etab
	touch $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/var/lib/nfs/state
	cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc
	ln -sf /proc/mounts mtab
	ln -sf rc.d/init.d init.d
	touch fstab
	echo "root:x:0:0:root:/root:/bin/bash" > passwd
	echo "root:x:0:root" > group
	echo "passwd:     files" > nsswitch.conf
	echo "shadow:     files" >> nsswitch.conf
	echo "group:      files" >> nsswitch.conf
	# cp libnss
	cp -aR /lib/libnss_files* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/	
	# installing hwdata, libkudzu and hwsetup
	cp -aR $OPENQRM_BUILD_TMP_DIR/openqrm-build/hwdata-knoppix/hwdata-install/* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/
	cp -a $OPENQRM_SOURCE_KUDZU_DIR/libkudzu.a $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
	cp -a $OPENQRM_SOURCE_HWSETUP_DIR/hwsetup $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/sbin/
	# add the libs hwsetup depends on
	for LIB in `openqrm_build_find_libs $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/sbin/hwsetup`; do
		LIB=`echo $LIB | cut -d'-' -f1 | cut -d'.' -f1`
		if [ "$LIB" != "/lib/" ]; then
			cp -a $LIB""* $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/lib/
		fi
	done

	# creating the initrd devices
	cp -a $OPENQRM_SOURCE_DIR_FULL_PATH/etc/build.conf/initrd-devices.conf $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc/
	rm -rf $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/dev
#	$OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/bin/busybox makedevs -d $OPENQRM_SOURCE_DIR_FULL_PATH/etc/build.conf/initrd-devices.conf $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/
	mkdir -p $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/dev
	cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/dev/
#	ln -sf tty0 systty
#	ln -sf ram1 ram

	# create rcS
	rm -f $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc/rc.d/init.d/rcS
	cat >> $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc/rc.d/init.d/rcS << EOF
#!/bin/bash
export SHELL=/bin/bash
export \$(eval cat /proc/cmdline)
echo "openQRM resource \$id is starting rcS" > /dev/console

EOF
	chmod +x $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc/rc.d/init.d/rcS

	# create inittab
	rm -f $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc/inittab
	cat >> $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/etc/inittab << EOF

# inittab
::askfirst:-/bin/bash
tty2::askfirst:-/bin/bash
tty3::askfirst:-/bin/bash
tty4::askfirst:-/bin/bash
::sysinit:/etc/init.d/rcS
::restart:/sbin/reboot

# Stuff to do before rebooting
::ctrlaltdel:/sbin/reboot
::shutdown:/sbin/halt

EOF
	cd $CURRENT_DIR
}


# function to create a tgz file out of the initroot/initrd-content
# -> this is for "make install" / installation phase
function openqrm_pack_default_initrd_template() {
	# pack
	CURRENT_DIR=`pwd`
	cd $OPENQRM_BUILD_TMP_DIR/openqrm-build/initroot/
	tar -czf $DESTINATION_DIR$OPENQRM_SERVER_BASE_DIR/openqrm/etc/templates/openqrm-initrd-default.tgz *
	cd $CURRENT_DIR
}


