#!/bin/bash
# this is the package function file for openQRM
# only functions needed for packaging should go in here

if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
	echo "ERROR: Please export OPENQRM_SERVER_BASE_DIR before sourcing $0"
	exit 1
fi
if [ "$OPENQRM_SOURCE_DIR" == "" ]; then
	echo "ERROR: Please export OPENQRM_SOURCE_DIR before sourcing $0"
	exit 1
fi

# get the openqrm-server configuration + functions
. $OPENQRM_SOURCE_DIR/etc/openqrm-server.conf
. $OPENQRM_SOURCE_DIR/include/openqrm-functions
for VAR in `cat $OPENQRM_SOURCE_DIR/etc/openqrm-server.conf | grep -v ^# | grep OPENQRM | cut -d'=' -f1`; do
	eval `export $VAR`
done

# get distribution
export OPENQRM_PACKAGE_DISTRIBUTION=`openqrm_get_distro`

function openqrm_check_requirements() {
	# check which dependencies to use
	if [ -f /etc/debian_version ]; then
		echo "Checking the requirements for Debian/Ubuntu based systems"
		OPENQRM_PACKAGE_TYPE=deb
		OPENQRM_DEPENDENCY_CHECK_COMMAND="dpkg -L"
		OPENQRM_PACKAGE_SYSTEM="debian"
		OPENQRM_PACKAGE_INSTALL_CMD="apt-get install"
	elif [ -f /etc/redhat-release ]; then
		echo "Checking the requirements for Redhat based systems"
		OPENQRM_PACKAGE_TYPE=rpm
		OPENQRM_DEPENDENCY_CHECK_COMMAND="rpm -qs"
		OPENQRM_PACKAGE_SYSTEM="redhat"
		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
	elif [ -f /etc/SuSE-release ]; then
		echo "Checking the requirements for Suse based systems"
		OPENQRM_PACKAGE_TYPE=rpm
		OPENQRM_DEPENDENCY_CHECK_COMMAND="rpm -qs"
		OPENQRM_PACKAGE_SYSTEM="suse"
		OPENQRM_PACKAGE_INSTALL_CMD="yum install"
	else
		echo "NOTICE: Could not find out which dependencies to use"
		echo "        Please make sure to have all needed components installed!"
		sleep 4
		echo "... Continuing anyway"
		return 0
	fi

	echo "openqrm-server requires : $OPENQRM_SERVER_DEPENDENCIES"
	for DEP in `echo $OPENQRM_SERVER_DEPENDENCIES | sed -e "s/,//g"`; do
		if $OPENQRM_DEPENDENCY_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
			echo "-> found $DEP installed"
		else
			echo "NOTICE: Trying to automatically install $DEP ..."
			if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
				echo "ERROR: $DEP could not be installed. Please install manually to continue"
				return 1
			fi
		fi
	done

	# get a list of plugins for checking their dependencies
	OPENQRM_PACKAGE_COMPONENT_LIST=`ls $OPENQRM_SERVER_BASE_DIR/openqrm/plugins`
	for OPENQRM_PLUGIN in $OPENQRM_PACKAGE_COMPONENT_LIST; do
		. $OPENQRM_SOURCE_DIR/plugins/$OPENQRM_PLUGIN/etc/openqrm-plugin-$OPENQRM_PLUGIN"".conf
		echo "openqrm-plugin-$OPENQRM_PLUGIN requires : `echo $OPENQRM_PLUGIN_DEPENDENCIES | sed -e "s/openqrm-server//g"`"
		for DEP in `echo $OPENQRM_PLUGIN_DEPENDENCIES | sed -e "s/,//g" | sed -e "s/openqrm-server//g"`; do
			if $OPENQRM_DEPENDENCY_CHECK_COMMAND $DEP 1>/dev/null 2>&1; then
				echo "-> found $DEP installed"
			else
				echo "NOTICE: Trying to automatically install $DEP ..."
				if ! $OPENQRM_PACKAGE_INSTALL_CMD $DEP; then
					echo "ERROR: $DEP could not be installed. Please install manually to continue"
					return 1
				fi
			fi
		done
	done
	echo "Checking for required components finished successfully"

}



function openqrm_package() {

	if [ -f /etc/debian_version ]; then
		OPENQRM_PACKAGE_TYPE=deb
	else
		OPENQRM_PACKAGE_TYPE=rpm
	fi
	echo "Creating $OPENQRM_PACKAGE_TYPE packages for openQRM-server ver. $OPENQRM_SERVER_VERSION for $OPENQRM_PACKAGE_DISTRIBUTION"

	# which components to build
	OPENQRM_PACKAGE_COMPONENT_LIST=`ls $OPENQRM_SOURCE_DIR/plugins | grep -v Makefile | grep -v CVS`
	OPENQRM_PACKAGE_COMPONENT_LIST="openqrm-server "`echo $OPENQRM_PACKAGE_COMPONENT_LIST | sed -e "s/\n//g"`
	echo "Packing the following components : $OPENQRM_PACKAGE_COMPONENT_LIST"

	########################## RPM PACKAGING ##########################
	
	# decide on rpm or deb package
	if [ "$OPENQRM_PACKAGE_TYPE" == "rpm" ]; then
		
		OPENQRM_PACKAGE_ARCHITECTURE=` uname -i`	
		for OPENQRM_PACKAGE_COMPONENT in $OPENQRM_PACKAGE_COMPONENT_LIST; do

			echo "Starting rpm packaging for $OPENQRM_PACKAGE_COMPONENT"
			# check if to package the openqrm-server or plugins
			if [ "$OPENQRM_PACKAGE_COMPONENT" == "openqrm-server" ]; then
				# we package the server (without any plugins)
				echo "Packaging the openQRM-server"
				OPENQRM_PACKAGE_NAME=$OPENQRM_PACKAGE_COMPONENT
				
				# set the server dependencies / decide on redhat or suse dependencies
				OPENQRM_PACKAGE_DEPENDENCIES=$OPENQRM_SERVER_DEPENDENCIES
				if [ -f /etc/redhat-release ]; then
					OPENQRM_PACKAGE_SUB_DIR="redhat"
				elif [ -f /etc/SuSE-release ]; then
					OPENQRM_PACKAGE_SUB_DIR="packages"
				fi

				# (re-)create the package tmp dir
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE

				# set postinst + prerm
				OPENQRM_PACKAGE_POSTINSTALL="sh /opt/openqrm/etc/init.d/openqrm-server.postinstall"
				OPENQRM_PACKAGE_PREREMOVE="sh /opt/openqrm/etc/init.d/openqrm-server.preremove"

				# set if files should include openqrm-server or just a plugin
				OPENQRM_BUILD_POSTINSTALL="rm -rf \$RPM_BUILD_ROOT/opt/openqrm/plugins/*"

				# create spec file from template
				cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/templates/openqrm-rpm.spec |	\
					sed -e "s/OPENQRM_PACKAGE_NAME/$OPENQRM_PACKAGE_NAME/g" |	\
					sed -e "s/OPENQRM_PACKAGE_VERSION/$OPENQRM_SERVER_VERSION/g" |	\
					sed -e "s/OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_ARCHITECTURE/g" |	\
					sed -e "s/OPENQRM_PACKAGE_DISTRIBUTION/$OPENQRM_PACKAGE_DISTRIBUTION/g" |	\
					sed -e "s/OPENQRM_PACKAGE_DEPENDENCIES/$OPENQRM_PACKAGE_DEPENDENCIES/g" |	\
					sed -e "s#OPENQRM_BUILD_POSTINSTALL#$OPENQRM_BUILD_POSTINSTALL#g" |	\
					sed -e "s#OPENQRM_PACKAGE_POSTINSTALL#$OPENQRM_PACKAGE_POSTINSTALL#g" |	\
					sed -e "s#OPENQRM_PACKAGE_PREREMOVE#$OPENQRM_PACKAGE_PREREMOVE#g"	\
					> $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_NAME.spec

				# create the source package
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION
				cp -aR ../src/* $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION/
				rm -rf `find $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION/ -name CVS`
				rm -f /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-server-$OPENQRM_SERVER_VERSION.tgz
				tar -C $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/ -czf /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-server-$OPENQRM_SERVER_VERSION.tgz openqrm-server-$OPENQRM_SERVER_VERSION/ 
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-server-$OPENQRM_SERVER_VERSION

				# build the rpm package
				rpmbuild -bb $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_NAME.spec

			else

				# we package a plugin
				echo "Packaging the openQRM plugin-$OPENQRM_PACKAGE_COMPONENT"
				OPENQRM_PACKAGE_NAME=openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT

				# get the plugin configuration
				. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/etc/$OPENQRM_PACKAGE_NAME"".conf

				# set the server dependencies / decide on redhat or suse dependencies
				OPENQRM_PACKAGE_DEPENDENCIES=$OPENQRM_PLUGIN_DEPENDENCIES
				if [ -f /etc/redhat-release ]; then
					OPENQRM_PACKAGE_SUB_DIR="redhat"
				elif [ -f /etc/SuSE-release ]; then
					OPENQRM_PACKAGE_SUB_DIR="packages"
				fi

				# (re-)create the package tmp dir
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE

				# set postinst + prerm
				OPENQRM_PACKAGE_POSTINSTALL="sh /opt/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/etc/init.d/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT.postinstall"
				OPENQRM_PACKAGE_PREREMOVE="sh /opt/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/etc/init.d/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT.preremove"

				# set if files should include openqrm-server or just a plugin
				OPENQRM_BUILD_POSTINSTALL="mkdir -p \$RPM_BUILD_ROOT/opt_plugin/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT \&\& cp -aR \$RPM_BUILD_ROOT/opt/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/* \$RPM_BUILD_ROOT/opt_plugin/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/ \&\& rm -rf \$RPM_BUILD_ROOT/opt \&\& mv \$RPM_BUILD_ROOT/opt_plugin \$RPM_BUILD_ROOT/opt"

				# create spec file from template
				cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/templates/openqrm-rpm.spec |	\
					sed -e "s/OPENQRM_PACKAGE_NAME/$OPENQRM_PACKAGE_NAME/g" |	\
					sed -e "s/OPENQRM_PACKAGE_VERSION/$OPENQRM_PLUGIN_VERSION/g" |	\
					sed -e "s/OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_ARCHITECTURE/g" |	\
					sed -e "s/OPENQRM_PACKAGE_DISTRIBUTION/$OPENQRM_PACKAGE_DISTRIBUTION/g" |	\
					sed -e "s/OPENQRM_PACKAGE_DEPENDENCIES/$OPENQRM_PACKAGE_DEPENDENCIES/g" |	\
					sed -e "s#OPENQRM_BUILD_POSTINSTALL#$OPENQRM_BUILD_POSTINSTALL#g" |	\
					sed -e "s#OPENQRM_PACKAGE_POSTINSTALL#$OPENQRM_PACKAGE_POSTINSTALL#g" |	\
					sed -e "s#OPENQRM_PACKAGE_PREREMOVE#$OPENQRM_PACKAGE_PREREMOVE#g"	\
					> $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_NAME.spec

				# create the source package
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION
				cp -aR ../src/* $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION/
				rm -rf `find $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION/ -name CVS`
				rm -f /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION.tgz
				tar -C $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/ -czf /usr/src/$OPENQRM_PACKAGE_SUB_DIR/SOURCES/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION.tgz openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_PLUGIN_VERSION/ 
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/source/openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT-$OPENQRM_SERVER_VERSION

				# build the deb package
				rpmbuild -bb $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_NAME.spec

			fi

		done

	########################## DEB PACKAGING ##########################

	elif [ "$OPENQRM_PACKAGE_TYPE" == "deb" ]; then

		OPENQRM_PACKAGE_ARCHITECTURE=`dpkg --print-architecture`	
		for OPENQRM_PACKAGE_COMPONENT in $OPENQRM_PACKAGE_COMPONENT_LIST; do

			echo "Starting deb packaging for $OPENQRM_PACKAGE_COMPONENT"

			# check if to package the openqrm-server or plugins
			if [ "$OPENQRM_PACKAGE_COMPONENT" == "openqrm-server" ]; then
				# we package the server (without any plugins)
				echo "Packaging the openQRM-server"
				OPENQRM_PACKAGE_NAME=$OPENQRM_PACKAGE_COMPONENT
				
				# set the server dependencies
				OPENQRM_PACKAGE_DEPENDENCIES=$OPENQRM_SERVER_DEPENDENCIES

				# (re-)create the package tmp dir
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN

				# create control file from template
				cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/templates/openqrm-deb.control |	\
					sed -e "s/OPENQRM_PACKAGE_NAME/$OPENQRM_PACKAGE_NAME/g" |	\
					sed -e "s/OPENQRM_PACKAGE_VERSION/$OPENQRM_SERVER_VERSION/g" |	\
					sed -e "s/OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_ARCHITECTURE/g" |	\
					sed -e "s/OPENQRM_PACKAGE_DEPENDENCIES/$OPENQRM_PACKAGE_DEPENDENCIES/g"	\
					> $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/control

				# create debian-binary file
				echo "2.0" > $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/debian-binary

				# create postinst + prerm
				cp $OPENQRM_SERVER_BASE_DIR/openqrm/etc/init.d/openqrm-server.postinstall $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/postinst
				chmod 0775 $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/postinst
				cp $OPENQRM_SERVER_BASE_DIR/openqrm/etc/init.d/openqrm-server.preremove $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/prerm
				chmod 0775 $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/prerm

				# copy package content
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_SERVER_BASE_DIR
				cp -aR $OPENQRM_SERVER_BASE_DIR/openqrm $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_SERVER_BASE_DIR/
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/*

				# build the deb package
				dpkg-deb --build $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_SERVER_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE

			else

				# we package a plugin
				echo "Packaging the openQRM plugin-$OPENQRM_PACKAGE_COMPONENT"
				OPENQRM_PACKAGE_NAME=openqrm-plugin-$OPENQRM_PACKAGE_COMPONENT

				# get the plugin configuration
				. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/etc/$OPENQRM_PACKAGE_NAME"".conf

				# set the plugins dependencies
				OPENQRM_PACKAGE_DEPENDENCIES=$OPENQRM_PLUGIN_DEPENDENCIES

				# (re-)create the package tmp dir
				rm -rf $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN

				# create control file from template
				cat $OPENQRM_SERVER_BASE_DIR/openqrm/etc/templates/openqrm-deb.control |	\
					sed -e "s/OPENQRM_PACKAGE_NAME/$OPENQRM_PACKAGE_NAME/g" |	\
					sed -e "s/OPENQRM_PACKAGE_VERSION/$OPENQRM_PLUGIN_VERSION/g" |	\
					sed -e "s/OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_PACKAGE_ARCHITECTURE/g" |	\
					sed -e "s/OPENQRM_PACKAGE_DEPENDENCIES/$OPENQRM_PACKAGE_DEPENDENCIES/g"	\
					> $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/control

				# create debian-binary file
				echo "2.0" > $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/debian-binary

				# create postinst + prerm
				cp $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/etc/init.d/$OPENQRM_PACKAGE_NAME"".postinstall $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/postinst
				chmod 0775 $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/postinst
				cp $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT/etc/init.d/$OPENQRM_PACKAGE_NAME"".preremove $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/prerm
				chmod 0775 $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/DEBIAN/prerm

				# copy package content
				mkdir -p $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_SERVER_BASE_DIR/openqrm/plugins
				cp -aR $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/$OPENQRM_PACKAGE_COMPONENT $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE/$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/

				# build the deb package
				dpkg-deb --build $OPENQRM_PACKAGE_TMP_DIR/openqrm-packaging/$OPENQRM_PACKAGE_NAME-$OPENQRM_PLUGIN_VERSION-$OPENQRM_PACKAGE_DISTRIBUTION.$OPENQRM_PACKAGE_ARCHITECTURE

			fi

		done
	
	else
		echo "ERROR: package type $OPENQRM_PACKAGE_TYPE not supported yet"
		exit 1
	fi

}



