#!/bin/bash
# init script for the openQRM dns plugin
OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/include/openqrm-plugin-dns-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/etc/openqrm-plugin-dns.conf

function openqrm_plugin_dns_start() {
	echo "Starting the openQRM dns-plugin"
	openqrm_plugin_dns_stop 1>/dev/null 2>&1
	$DNS_INIT start
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/dns/.running
	return $RET
	
}


function openqrm_plugin_dns_stop() {
	echo "Stopping the openQRM dns-plugin"
	$DNS_INIT stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/dns/.running
	return 0
}


function openqrm_plugin_dns_init() {
	echo "Initializing the openQRM dns-plugin"
	openqrm_server_get_config
	OPENQRM_SERVER_IP_LAST_BYTE=`echo $OPENQRM_SERVER_IP_ADDRESS | cut -d'.' -f 4`
	OPENQRM_SERVER_IP_FIRST_BYTE=`echo $OPENQRM_SERVER_IP_ADDRESS | cut -d'.' -f1`
	OPENQRM_SERVER_IP_SECOND_BYTE=`echo $OPENQRM_SERVER_IP_ADDRESS | cut -d'.' -f2`
	OPENQRM_SERVER_IP_THIRD_BYTE=`echo $OPENQRM_SERVER_IP_ADDRESS | cut -d'.' -f3`
	OPENQRM_SERVER_IP_FIRSTS_BYTES_REV="$OPENQRM_SERVER_IP_THIRD_BYTE.$OPENQRM_SERVER_IP_SECOND_BYTE.$OPENQRM_SERVER_IP_FIRST_BYTE"

	# take backups of an eventual existing config
	if [ ! -f /etc/bind/named.conf.local.openqrm-dns-plugin.backup ]; then
		cp -f /etc/bind/named.conf.local /etc/bind/named.conf.local.openqrm-dns-plugin.backup
	fi

	# preparing bind config
	mkdir -p /etc/bind/zones/
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/etc/bind/zones
	
	# named.conf local
	cat $DNS_NAMED_LOCAL_TEMPLATE |	\
		sed -e "s/@@OPENQRM_SERVER_IP_FIRSTS_BYTES_REV@@/$OPENQRM_SERVER_IP_FIRSTS_BYTES_REV/g" |	\
			sed -e "s/@@OPENQRM_SERVER_DOMAIN@@/$OPENQRM_SERVER_DOMAIN/g" > $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/etc/bind/named.conf.local
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/etc/bind/named.conf.local /etc/bind/named.conf.local
	
	# in db
	cat $DNS_INDB_TEMPLATE |	\
		sed -e "s/@@OPENQRM_SERVER_DOMAIN@@/$OPENQRM_SERVER_DOMAIN/g" |	\
		sed -e "s/@@OPENQRM_SERVER_IP_ADDRESS@@/$OPENQRM_SERVER_IP_ADDRESS/g" |	\
		sed -e "s/@@OPENQRM_SERVER_IP_LAST_BYTE@@/$OPENQRM_SERVER_IP_LAST_BYTE/g" > $DNS_INDB
	DNS_INDB_FSNAME=`basename $DNS_INDB`
	ln -sf $DNS_INDB /etc/bind/zones/$DNS_INDB_FSNAME

	# rev db
	cat $DNS_REVDB_TEMPLATE |	\
		sed -e "s/@@OPENQRM_SERVER_DOMAIN@@/$OPENQRM_SERVER_DOMAIN/g" |	\
		sed -e "s/@@OPENQRM_SERVER_IP_ADDRESS@@/$OPENQRM_SERVER_IP_ADDRESS/g" |	\
		sed -e "s/@@OPENQRM_SERVER_IP_LAST_BYTE@@/$OPENQRM_SERVER_IP_LAST_BYTE/g" > $DNS_REVDB
	DNS_REVDB_FSNAME=`basename $DNS_REVDB`
	ln -sf $DNS_REVDB /etc/bind/zones/$DNS_REVDB_FSNAME

	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/dns

	return 0
}


function openqrm_plugin_dns_uninstall() {
	echo "Uninstalling the openQRM dns-plugin"
	openqrm_plugin_dns_stop

	# cleaning up + restore bind config
	rm -f /etc/bind/zones/$OPENQRM_SERVER_DOMAIN.*.db
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/dns/etc/bind/zones/$OPENQRM_SERVER_DOMAIN-*.db

	# restore eventual existing config
	if [ -f /etc/bind/named.conf.local.openqrm-dns-plugin.backup ]; then
		rm -f /etc/bind/named.conf.local
		cp -f /etc/bind/named.conf.local.openqrm-dns-plugin.backup /etc/bind/named.conf.local
	fi

	# unlinking the web dir
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/dns
}



case "$1" in
	start)
		openqrm_plugin_dns_start
		;;
	stop)
		openqrm_plugin_dns_stop
		;;
	restart)
		openqrm_plugin_dns_stop
		sleep 1
		openqrm_plugin_dns_start
		;;
	init)
		openqrm_plugin_dns_init
		;;
	uninstall)
		openqrm_plugin_dns_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?


