#!/bin/bash
# this is the functions file for the lvm-storage-plugin


# iscsi-target config file
IETDCONF=/etc/ietd.conf
# vblade config file
VBLADECONF=/etc/vblade.conf
# some definitions
DEFAULT_IMAGE_SIZE=5000
LVM_MGMT_LOCK_FILE=/var/run/lvm-storage/lvm-storage-plugin.lock
LVM_MGMT_LOCK_DELAY=5
LVM_MGMT_LOCK_RETRY=100
LVM_MGMT_LOCK_TIMEOUT=500
MAX_UMOUNT_LOOP=5
LV_SIZE_DEFAULT=5000
ISCSI_TARGET_URL=http://iscsitarget.sourceforge.net/
AOE_AUTHENTICATED_MAC="00:00:00:00:00:00"
IMAGE_LUN=1

################ common lvm-storage functions

# logs for lvm_storage
function lvm_storage_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "lvm-storage plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function lvm_storage_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $LVM_MGMT_LOCK_FILE` ]; then
		mkdir -p `dirname $LVM_MGMT_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $LVM_MGMT_LOCK_DELAY -r $LVM_MGMT_LOCK_RETRY -l $LVM_MGMT_LOCK_TIMEOUT $LVM_MGMT_LOCK_FILE
				RET=$?
				lvm_storage_log lvm_storage_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $LVM_MGMT_LOCK_FILE
				RET=$?
				lvm_storage_log lvm_storage_lock "Released the lock"
				return $RET
				;;
		*)
			lvm_storage_log lvm_storage_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ lvm-storage functions

################ lvm-nfs ###################################


function manage_fstab() {
	case "$1" in
		add)
			echo "/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME    /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME      ext3    defaults        1 1" >> /etc/fstab
			;;
		remove)
			sed -i -e "s#^/dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME.*##g" /etc/fstab
			;;
	esac
}


function manage_nfs() {
	case "$1" in
		add)
			OPENQRM_SERVER=$3
			if [ "$2" != "snap" ]; then
				lvm_storage_log manage_nfs "NOTICE: creating ext3 filesytem on /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME"
				if ! mkfs.ext3 -F /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME; then
					lvm_storage_log lvm-storage-functions "ERROR: Could not create ext3 filesytem on /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME"
					manage_fstab remove
					lvm_storage_lock release
					return 1
				fi
			fi
			mkdir -p /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
			if ! `mount /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME`; then
				lvm_storage_log lvm-storage-functions "ERROR: Could not mount /dev/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME at /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME"
				manage_fstab remove
				lvm_storage_lock release
				return 1
			fi
			echo "/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME	$OPENQRM_SERVER(rw,insecure,no_root_squash,async)" >> /etc/exports
			if [ -x /etc/init.d/nfs ]; then
				/etc/init.d/nfs reload
			elif [ -x /etc/init.d/nfs-kernel-server ]; then
				/etc/init.d/nfs-kernel-server reload
			else
				lvm_storage_log lvm-storage-functions "WARNING: Could not find nfs-server init script !"
				lvm_storage_lock release
				return 1
			fi
			;;
		remove)
			sed -i -e "s#^/$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME.*##g" /etc/exports
			if [ -x /etc/init.d/nfs ]; then
				/etc/init.d/nfs reload
			elif [ -x /etc/init.d/nfs-kernel-server ]; then
				/etc/init.d/nfs-kernel-server reload
			else
				lvm_storage_log lvm-storage-functions "WARNING: Could not find nfs-server init script !"
				lvm_storage_lock release
				return 1
			fi
			while ! `umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME`; do
				echo "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME, trying again ..."
				lvm_storage_log lvm-storage-functions "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME, trying again ..."
				if [ "$UMOUNT_LOOP" = "$MAX_UMOUNT_LOOP" ]; then
					echo "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME. Giving up !!!" 2>1
					lvm_storage_log lvm-storage-functions "ERROR: Could not umount /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME. Giving up !!!"
					manage_fstab remove
					lvm_storage_lock release
					return 20
				fi
				UMOUNT_LOOP=$(( UMOUNT_LOOP + 1 ))
				sleep 2
			done
			rmdir /$LVM_STORAGE_SERVER_VOLUME_GROUP/$LVM_IMAGE_NAME
			;;
		auth)
			AUTH_IP=$2
			sed -i -e "s#^$LVM_IMAGE_ROOTDEVICE.*#$LVM_IMAGE_ROOTDEVICE	$AUTH_IP(rw,insecure,no_root_squash,async)#g" /etc/exports
			sed -i '/^$/d' /etc/exports
			if [ -x /etc/init.d/nfs ]; then
				/etc/init.d/nfs reload
			elif [ -x /etc/init.d/nfs-kernel-server ]; then
				/etc/init.d/nfs-kernel-server reload
			else
				lvm_storage_log lvm-storage-functions "WARNING: Could not find nfs-server init script !"
				lvm_storage_lock release
				return 1
			fi
			;;
	esac
}



################ lvm-iscsi ###################################


function check_iscsi_target() {
	# iscsi-target installed ?
	if ! ls $IETDCONF 1>/dev/null; then
		echo "ERROR: Iscsi Enterprise Target not installed !"
		echo "ERROR: For managing Iscsi filesystem-images please download and install from"
		echo "       $ISCSI_TARGET_URL"
		lvm_storage_log lvm-storage-functions "ERROR: Iscsi Enterprise Target not installed !"
		lvm_storage_lock release
		return 1
	fi			
}


function manage_iscsi() {

	if ! check_iscsi_target; then
		return
	fi
	case "$1" in
		add)
			IMAGE_PASS=$3
			if [ "$2" != "snap" ]; then
				# create fs, currently static all ext3
				mkfs.ext3 -F /dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME
			fi
			echo "Target $LVM_IMAGE_NAME" >> $IETDCONF
			echo "	IncomingUser $LVM_IMAGE_NAME $IMAGE_PASS" >> $IETDCONF
			echo "	Lun $IMAGE_LUN Path=/dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME,Type=fileio" >> $IETDCONF
			LAST_TID=`grep tid: /proc/net/iet/volume | cut -d':' -f2 | awk {' print $1 '} | sort | tail -n1`
			NEW_TID=$(( $LAST_TID + 1 ))
			# dynamically add new target
			if ! ietadm --op new --tid=$NEW_TID --params Name=$LVM_IMAGE_NAME; then
				lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not create new target !"
				lvm_storage_lock release
				return 1
			fi
			# set path to lvm device in the new target
			if ! ietadm --op new --tid=$NEW_TID --lun=$IMAGE_LUN --params Path=/dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME; then
				lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not set lvm-path in new target !"
				lvm_storage_lock release
				return 1
			fi
			# auth target
			if ! ietadm --op new --tid=$NEW_TID --user --params IncomingUser=$LVM_IMAGE_NAME,Password=$IMAGE_PASS; then
				lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not set username/password in new target !"
				lvm_storage_lock release
				return 1
			else
				lvm_storage_log lvm-storage-functions "lvm-iscsi created new target $LVM_IMAGE_NAME !"
			fi
			;;
		remove)
			sed -i -e "s#.*$LVM_IMAGE_NAME.*##g" $IETDCONF
			TID_TO_REMOVE=`cat /proc/net/iet/volume | grep "name:$LVM_IMAGE_NAME" | cut -d':' -f2 | awk {' print $1 '}`
			OPEN_SESSION=`cat /proc/net/iet/session | grep -w ^tid:$TID_TO_REMOVE -A1 | grep sid: | cut -d':' -f2 | awk {' print $1 '}`
			if [ "$OPEN_SESSION" != "" ]; then
				# first remove active session (does not support multiple sessions yet)
				if ! ietadm --op delete --tid=$TID_TO_REMOVE --sid=$OPEN_SESSION --cid=0; then
					lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not remove session $OPEN_SESSION for tid $TID_TO_REMOVE !"
					lvm_storage_lock release
					return 1
				else
					lvm_storage_log lvm-storage-functions "lvm-iscsi removed session $OPEN_SESSION for tid $TID_TO_REMOVE !"
				fi
			fi
			# remove lun
			if ! ietadm --op delete --tid=$TID_TO_REMOVE --lun=$IMAGE_LUN; then
				lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not remove lun $IMAGE_LUN for tid $TID_TO_REMOVE !"
				lvm_storage_lock release
				return 1
			fi
			# remove target dynamically
			if ! ietadm --op delete --tid=$TID_TO_REMOVE; then
				lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not remove target tid $TID_TO_REMOVE !"
				lvm_storage_lock release
				return 1
			else
				lvm_storage_log lvm-storage-functions "lvm-iscsi removed target tid $TID_TO_REMOVE !"
			fi
			;;
		auth)
			IMAGE_PASS=$2
			IMAGE_AUTHNAME=`echo $LVM_IMAGE_ROOTDEVICE | cut -d'/' -f3`
			sed -i -e "s#IncomingUser $IMAGE_AUTHNAME .*#IncomingUser $IMAGE_AUTHNAME $IMAGE_PASS#g" $IETDCONF
			sed -i '/^$/d' $IETDCONF
			TID_TO_AUTH=`cat /proc/net/iet/volume | grep "name:$IMAGE_AUTHNAME" | cut -d':' -f2 | awk {' print $1 '}`
			if [ "$TID_TO_AUTH" == "" ]; then
				lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not find target $IMAGE_AUTHNAME to update the authentication !"
				lvm_storage_lock release
				return 1
			fi
			if ! ietadm --op new --tid=$TID_TO_AUTH --user --params IncomingUser=$IMAGE_AUTHNAME,Password=$IMAGE_PASS; then
				lvm_storage_log lvm-storage-functions "ERROR: lvm-iscsi could not find target $IMAGE_AUTHNAME to update the authentication !"
				lvm_storage_lock release
				return 1
			else
				lvm_storage_log lvm-storage-functions "lvm-iscsi updated the authentication for target $IMAGE_AUTHNAME !"
			fi
			;;
	esac
}




################ lvm-aoe ###################################



function check_vblade() {
	# vblade installed ?
	if ! which vbladed 1>/dev/null; then
		echo "ERROR: Vblade is not installed !"
		echo "ERROR: For managing Aoe filesystem-images please install 'vblade'"
		lvm_storage_log lvm-storage-functions "ERROR: Vblade is not installed !"
		lvm_storage_lock release
		return 1
	fi			
}


function manage_vblade() {

	if ! check_vblade; then
		return
	fi
	if [ ! -f $VBLADECONF ]; then
		mkdir -p `dirname $VBLADECONF`
		echo "# this is the vblade configuration file created by openQRM" > $VBLADECONF
		echo "" >> $VBLADECONF
	fi
	
	case "$1" in
		add)
			if [ "$2" != "snap" ]; then
				# create fs, currently static all ext3
				mkfs.ext3 -F /dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME
			fi
			# slots are dynamic
			AOE_SLOT=`cat $VBLADECONF | grep -v '^#' | awk {' print $3 '} | sort -n -r | head -n 1`
			AOE_SLOT=$(( AOE_SLOT + 1 ))
			if [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
				. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
				AOE_INTERFACE=$OPENQRM_SERVER_INTERFACE
			else
				AOE_INTERFACE=`ifconfig | grep $resource_mac | awk {' print $1 '} | tail -1`
			fi
			echo "$AOE_INTERFACE $AOE_SHELF $AOE_SLOT /dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME $AOE_AUTHENTICATED_MAC" >> $VBLADECONF
			sed -i '/^$/d' $VBLADECONF
			# start vbladed
			SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
			screen -dmS $SCREEN_NAME vblade -m $AOE_AUTHENTICATED_MAC $AOE_SHELF $AOE_SLOT $AOE_INTERFACE /dev/mapper/$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME
			;;
		auth)
			AUTHENTICATED_MAC=$2
			AOE_SLOT=`echo $LVM_IMAGE_ROOTDEVICE | cut -d'.' -f2`
			AOE_SHELF=`echo $LVM_IMAGE_ROOTDEVICE | cut -d'.' -f1 | sed -e "s#/dev/etherd/e##g"`
			if grep "$AOE_SHELF $AOE_SLOT" $VBLADECONF 1>/dev/null; then
				AOE_INTERFACE=`cat $VBLADECONF | grep -v "#" | grep "$AOE_SHELF $AOE_SLOT" | awk {' print $1'}`
				AOE_IMAGE_ROOTDEVICE_PATH=`cat $VBLADECONF | grep "$AOE_SHELF $AOE_SLOT" | awk {' print $4 '}`
				sed -i -e "s#$AOE_IMAGE_ROOTDEVICE_PATH .*#$AOE_IMAGE_ROOTDEVICE_PATH $AUTHENTICATED_MAC#g" $VBLADECONF
				sed -i '/^$/d' $VBLADECONF
				for VBLADE_PID in `ps ax | grep vblade | grep -w $AOE_IMAGE_ROOTDEVICE_PATH | awk {' print $1 '}`; do
					kill $VBLADE_PID
				done
				sync			
				# start vbladed
				SCREEN_NAME=`date +%T%x | sed -e "s/://g" | sed -e "s#/##g"`
				screen -dmS $SCREEN_NAME vblade -m $AUTHENTICATED_MAC $AOE_SHELF $AOE_SLOT $AOE_INTERFACE $AOE_IMAGE_ROOTDEVICE_PATH
			fi
			;;
		remove)
			for VBLADE_PID in `ps ax | grep vblade | grep -w $LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME | awk {' print $1 '}`; do
				kill $VBLADE_PID
			done
			sync
			sed -i -e "s#.*$LVM_STORAGE_SERVER_VOLUME_GROUP-$LVM_IMAGE_NAME.*##g" $VBLADECONF
			sed -i '/^$/d' $VBLADECONF
			;;
	esac
}










