#!/bin/bash
# this is the functions file for the vmware-server-plugin

. /var/openqrm/openqrm-resource.conf

################ common vmware-server functions

# logs for vmware-server
function vmware_server_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "vmware-server plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function vmware_server_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $LVM_MGMT_LOCK_FILE` ]; then
		mkdir -p `dirname $LVM_MGMT_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $LVM_MGMT_LOCK_DELAY -r $LVM_MGMT_LOCK_RETRY -l $LVM_MGMT_LOCK_TIMEOUT $LVM_MGMT_LOCK_FILE
				RET=$?
				vmware_server_log vmware_server_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $LVM_MGMT_LOCK_FILE
				RET=$?
				vmware_server_log vmware_server_lock "Released the lock"
				return $RET
				;;
		*)
			vmware_server_log vmware_server_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ vmware-server functions






