#!/bin/bash
# this is the functions file for the vmware-server-plugin
VMWARE_SERVER_LOCK_FILE=/var/run/openqrm/vmware-server-plugin.lock
VMWARE_SERVER_LOCK_DELAY=5
VMWARE_SERVER_LOCK_RETRY=100
VMWARE_SERVER_LOCK_TIMEOUT=500
################ common vmware-server functions

# logs for vmware-server
function vmware_server_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "vmware-server plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function vmware_server_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $VMWARE_SERVER_LOCK_FILE` ]; then
		mkdir -p `dirname $VMWARE_SERVER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $VMWARE_SERVER_LOCK_DELAY -r $VMWARE_SERVER_LOCK_RETRY -l $VMWARE_SERVER_LOCK_TIMEOUT $VMWARE_SERVER_LOCK_FILE
				RET=$?
				vmware_server_log vmware_server_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $VMWARE_SERVER_LOCK_FILE
				RET=$?
				vmware_server_log vmware_server_lock "Released the lock"
				return $RET
				;;
		*)
			vmware_server_log vmware_server_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ vmware-server functions






