#!/bin/bash
# this is the functions file for the puppet-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#
PUPPET_MANAGER_LOCK_FILE=/var/run/openqrm/puppet-plugin.lock
PUPPET_MANAGER_LOCK_DELAY=5
PUPPET_MANAGER_LOCK_RETRY=100
PUPPET_MANAGER_LOCK_TIMEOUT=500
################ common puppet functions

# logs for puppet
function puppet_manager_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "puppet plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function puppet_manager_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $PUPPET_MANAGER_LOCK_FILE` ]; then
		mkdir -p `dirname $PUPPET_MANAGER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $PUPPET_MANAGER_LOCK_DELAY -r $PUPPET_MANAGER_LOCK_RETRY -l $PUPPET_MANAGER_LOCK_TIMEOUT $PUPPET_MANAGER_LOCK_FILE
				RET=$?
				puppet_manager_log puppet_manager_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $PUPPET_MANAGER_LOCK_FILE
				RET=$?
				puppet_manager_log puppet_manager_lock "Released the lock"
				return $RET
				;;
		*)
			puppet_manager_log puppet_manager_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ puppet functions






