#!/bin/bash
# init script for the openQRM tmpfs-storage-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/tmpfs-storage/include/openqrm-plugin-tmpfs-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/tmpfs-storage/etc/openqrm-plugin-tmpfs-storage.conf



function openqrm_plugin_tmpfs_storage_start() {
	openqrm_plugin_tmpfs_storage_stop 1>/dev/null 2>&1
	echo "Starting the openQRM tmpfs-storage-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/tmpfs-storage/.running
}


function openqrm_plugin_tmpfs_storage_stop() {
	echo "Stopping the openQRM tmpfs-storage-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/tmpfs-storage/.running
}

function openqrm_plugin_tmpfs_storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "tmpfs-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "tmpfs-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM tmpfs-storage-plugin"
	openqrm_plugin_tmpfs_storage_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD tmpfs-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/tmpfs-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.tmpfs-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.tmpfs-deployment.php

}

function openqrm_plugin_tmpfs_storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "tmpfs-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "tmpfs-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM tmpfs-storage-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD tmpfs-deployment tmpfs-deployment "Tmpfs-root deployment" tmpfs-storage "temporary In-Memory Storage"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/tmpfs-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/tmpfs-storage
	# linking the root mount hook
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/tmpfs-storage/web/root-mount.tmpfs-deployment
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/tmpfs-storage/web/root-mount.tmpfs-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.tmpfs-deployment
	# linking the default image-parameters
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/tmpfs-storage/web/image.tmpfs-deployment.php $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image.tmpfs-deployment.php
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_tmpfs_storage_start
		;;
	stop)
		openqrm_plugin_tmpfs_storage_stop
		;;
	restart)
		openqrm_plugin_tmpfs_storage_stop
		sleep 1
		openqrm_plugin_tmpfs_storage_start
		;;
	init)
		openqrm_plugin_tmpfs_storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_tmpfs_storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




