#!/bin/bash
# this is the boot-service init script for the Linux-VServer-hosts

export `eval cat /proc/cmdline`	
. /var/openqrm/openqrm-resource.conf
export OPENQRM_SERVER_BASE_DIR=$resource_basedir
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions


function linux_vserver_start() {
	echo "Starting the openQRM linux-vserver-plugin"
	linux_vserver_stop 1>/dev/null 2>&1
	# download the initrd
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates
	if ! wget -q -O $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/etc/templates/openqrm-initrd-default.tgz http://$resource_openqrmserver/openqrm/boot-service/openqrm-initrd-default.tgz; then
		echo "ERROR: Could not download http://$resource_openqrmserver/openqrm/boot-service/openqrm-initrd-default.tgz"
		return 1
	fi
}


function linux_vserver_stop() {
	echo "Stopping the openQRM linux-vserver-plugin"
}


case "$1" in
	start)
		linux_vserver_start
		;;
	stop)
		linux_vserver_stop
		;;
	restart)
		linux_vserver_stop
		sleep 1
		linux_vserver_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













