#!/bin/bash
# openQRM postgres-specfic functions
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
	echo "ERROR: Please export OPENQRM_SERVER_BASE_DIR before sourcing $0"
	exit 1
fi

. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
OPENQRM_DATABASE_INIT="$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/postgres/openqrm-postgres-init.sql"
	OPENQRM_DATABASE_INIT_TMP=/tmp/openqrm-postgres-init.sql

if ! which psql 1>/dev/null 2>&1; then
	echo "ERROR: Postgres client 'psql' not installed/found on this system"
	exit 1
else
	POSTGRES_CLIENT=`which psql`
fi
if ! which pg_dump 1>/dev/null 2>&1; then
	echo "ERROR: Postgres 'pg_dump' not installed/found on this system"
	exit 1
else
	POSTGRES_DUMP=`which pg_dump`
fi


function initialize_database() {
	echo "Initializing the openQRM-database"
	cat $OPENQRM_DATABASE_INIT |	\
		sed -e "s/OPENQRM_SERVER_IP_ADDRESS/$OPENQRM_SERVER_IP_ADDRESS/g"	\
		> $OPENQRM_DATABASE_INIT_TMP
	chmod 777 $OPENQRM_DATABASE_INIT_TMP
	su - postgres -c "dropdb $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
	su - postgres -c "createdb $OPENQRM_DATABASE_NAME"
	su - postgres -c "$POSTGRES_CLIENT -d $OPENQRM_DATABASE_NAME --set openqrmdbuser=$OPENQRM_DATABASE_USER -f $OPENQRM_DATABASE_INIT_TMP"
	RET=$?
	rm -f $OPENQRM_DATABASE_INIT_TMP
	return $RET
}



function backup_database() {
	local SQL=$1
	echo "Creating backup of the openQRM-database at $SQL"
	su - postgres -c "$POSTGRES_DUMP -U $OPENQRM_DATABASE_USER $OPENQRM_DATABASE_NAME > $SQL"
	return $RET

}

function restore_database() {
	local SQL=$1
	echo "Restoring the openQRM-database from $SQL"
	su - postgres -c "$POSTGRES_CLIENT -d $OPENQRM_DATABASE_NAME --set openqrmdbuser=$OPENQRM_DATABASE_USER -f $SQL"
	return $RET
}

function drop_database() {
	echo "Dropping the openQRM-database"
	su - postgres -c "dropdb $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
	return $RET
}


case "$1" in
	init)
		initialize_database
		;;
	backup)
		backup_database $2
		;;
	restore)
		restore_database $2
		;;
	drop)
		drop_database
		;;
esac
