#!/bin/bash
# init script for the openQRM local-deployment-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/include/openqrm-plugin-local-deployment-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/etc/openqrm-plugin-local-deployment.conf


# TODO
# we must find a proper solution to start/stop 
# the plugin with correct user-authentication
# -> for now using openqrm user static

function openqrm_plugin_local-deployment_start() {
	echo "Starting the openQRM local-deployment-plugin"
	openqrm_server_add_deployment_type openqrm openqrm local "Local-root deployment"
}


function openqrm_plugin_local-deployment_stop() {
	echo "Stopping the openQRM local-deployment-plugin"
	openqrm_server_remove_deployment_type openqrm openqrm local

}

function openqrm_plugin_local-deployment_uninstall() {
	echo "Uninstalling the openQRM local-deployment-plugin"
	openqrm_plugin_local-deployment_stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-deployment
}

function openqrm_plugin_local-deployment_init() {
	echo "Initializing the openQRM local-deployment-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/web/root-mount.local-deployment
	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/web/root-mount.local-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-deployment
}


case "$1" in
	start)
		openqrm_plugin_local-deployment_start
		;;
	stop)
		openqrm_plugin_local-deployment_stop
		;;
	restart)
		openqrm_plugin_local-deployment_stop
		sleep 1
		openqrm_plugin_local-deployment_start
		;;
	init)
		openqrm_plugin_local-deployment_init
		;;
	uninstall)
		openqrm_plugin_local-deployment_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




