#!/bin/bash
# init script for the openQRM local-deployment-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/include/openqrm-plugin-local-deployment-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/etc/openqrm-plugin-local-deployment.conf


function openqrm_plugin_local-deployment_start() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "local-deployment: Please give a username to start the plugin : "
		read USERNAME
		echo	
		echo -n "local-deployment: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Starting the openQRM local-deployment-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD local "Local-deployment"
}


function openqrm_plugin_local-deployment_stop() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "local-deployment: Please give a username to stop the plugin : "
		read USERNAME
		echo	
		echo -n "local-deployment: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Stopping the openQRM local-deployment-plugin"
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD local

}

function openqrm_plugin_local-deployment_uninstall() {
	echo "Uninstalling the openQRM local-deployment-plugin"
	openqrm_plugin_local-deployment_stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-deployment
}

function openqrm_plugin_local-deployment_init() {
	echo "Initializing the openQRM local-deployment-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/web/root-mount.local-deployment
	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/web/root-mount.local-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.local-deployment
	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/local-deployment/web/partimage $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/partimage
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_local-deployment_start $USER $PASS
		;;
	stop)
		openqrm_plugin_local-deployment_stop $USER $PASS
		;;
	restart)
		openqrm_plugin_local-deployment_stop
		sleep 1
		openqrm_plugin_local-deployment_start
		;;
	init)
		openqrm_plugin_local-deployment_init
		;;
	uninstall)
		openqrm_plugin_local-deployment_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




