#!/bin/bash
# init script for the openQRM nfs-deployment-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-deployment/include/openqrm-plugin-nfs-deployment-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-deployment/etc/openqrm-plugin-nfs-deployment.conf



function openqrm_plugin_nfs-deployment_start() {
	echo "Starting the openQRM nfs-deployment-plugin"
}


function openqrm_plugin_nfs-deployment_stop() {
	echo "Stopping the openQRM nfs-deployment-plugin"
}

function openqrm_plugin_nfs-deployment_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "nfs-deployment: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "nfs-deployment: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM nfs-deployment-plugin"
	openqrm_plugin_nfs-deployment_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD nfs
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.nfs-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.nfs-menu.html
	
}

function openqrm_plugin_nfs-deployment_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "nfs-deployment: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "nfs-deployment: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM nfs-deployment-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD nfs "Nfs-root deployment"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-deployment/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-deployment/web/root-mount.nfs-deployment
	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-deployment/web/root-mount.nfs-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.nfs-deployment
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nfs-deployment/web/image-deployment-parameter.nfs-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.nfs-menu.html
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_nfs-deployment_start
		;;
	stop)
		openqrm_plugin_nfs-deployment_stop
		;;
	restart)
		openqrm_plugin_nfs-deployment_stop
		sleep 1
		openqrm_plugin_nfs-deployment_start
		;;
	init)
		openqrm_plugin_nfs-deployment_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_nfs-deployment_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




