#!/bin/bash
# this is the boot-service init script for the Kvm-server hosts

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/openqrm-plugin-kvm-functions
if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
	. $OPENQRM_RESOURCE_PARAMETER_FILE
	OPENQRM_SERVER_IP=$resource_openqrmserver
elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
	openqrm_server_get_config
	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
fi


function kvm_start() {
	echo "Starting the openQRM kvm-plugin"

	# preparing the nic-bios in case the openQRM server itself is the kvm-host
	if [ ! -d /usr/share/kvm/ ]; then
		mkdir -p /usr/share/kvm
	fi
	if [ -f /usr/share/kvm/pxe-e1000.bin ] && [ ! -f /usr/share/kvm/pxe-e1000.bin.openqrm-backup ]; then
		cp -f /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-e1000.bin.openqrm-backup
	fi
	if [ -f /usr/share/kvm/pxe-rtl8139.bin ] && [ ! -f /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup ]; then
		cp -f /usr/share/kvm/pxe-rtl8139.bin /usr/share/kvm/pxe-rtl8139.bin.openqrm-backup
	fi
	tar -C /usr/share/kvm/ -xzf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/kvm/include/pxe/kvm-nic-bios-1.0.tgz
	chown root:root /usr/share/kvm/pxe-e1000.bin /usr/share/kvm/pxe-rtl8139.bin

	# be sure to have the tun device
	if [ ! -f /dev/tun ]; then
		mknod /dev/tun c 10 200
	fi
	depmod -a
	modprobe tun

	# check that bridging is enabled
	if ! which brctl 1>/dev/null; then
		kvm_log kvm_start "ERROR: brctl is not installed! Please install bridge-utils."
		exit 1
	fi
	if ! which kvm 1>/dev/null; then
		kvm_log kvm_start "ERROR: kvm is not installed! Please install kvm."
		exit 1
	fi
	# does bridge already exist ?
	if ! brctl show | grep $OPENQRM_KVM_BRIDGE 1>/dev/null; then
		kvm_log kvm_start "NOTICE: Kvm network-bridge $OPENQRM_KVM_BRIDGE not active yet. Activating now ..."
		BRIDGE_INTERFACE=`ifconfig -a | grep -A1 $resource_mac | grep -B1 $resource_ip | head -n1 | awk {' print $1 '}`
		if [ "$BRIDGE_INTERFACE" == "" ]; then
			kvm_log kvm_start "ERROR: Could not find openQRM-interface to create the kvm network-bridge on!"
			exit 1
		fi
		# create the bridge
		brctl addbr $OPENQRM_KVM_BRIDGE
		brctl setfd $OPENQRM_KVM_BRIDGE 0
		brctl sethello $OPENQRM_KVM_BRIDGE 2
		brctl setmaxage $OPENQRM_KVM_BRIDGE 12
		brctl stp $OPENQRM_KVM_BRIDGE off
		brctl addif $OPENQRM_KVM_BRIDGE $BRIDGE_INTERFACE
		ifconfig $OPENQRM_KVM_BRIDGE $resource_ip up
		ifconfig $BRIDGE_INTERFACE 0.0.0.0 up
		kvm_log kvm_start "NOTICE: Kvm network-bridge $OPENQRM_KVM_BRIDGE now active."
	fi


}


function kvm_stop() {
	echo "Stopping the openQRM kvm-plugin"

}





case "$1" in
	start)
		kvm_start
		;;
	stop)
		kvm_stop
		;;
	restart)
		kvm_stop
		sleep 1
		kvm_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













