#!/bin/bash
# this is the functions file for the windows-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#


# some definitions
DEFAULT_IMAGE_SIZE=5000
WINDOWS_LOCK_FILE=/var/run/windows/windows-plugin.lock
WINDOWS_LOCK_DELAY=5
WINDOWS_LOCK_RETRY=100
WINDOWS_LOCK_TIMEOUT=500

################ common windows functions

# logs for windows
function windows_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "windows plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function windows_lock() {
	local COMMAND=$1
	local RET=1

	if [ ! -d `dirname $WINDOWS_LOCK_FILE` ]; then
		mkdir -p `dirname $WINDOWS_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $WINDOWS_LOCK_DELAY -r $WINDOWS_LOCK_RETRY -l $WINDOWS_LOCK_TIMEOUT $WINDOWS_LOCK_FILE
				RET=$?
				windows_log windows_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $WINDOWS_LOCK_FILE
				RET=$?
				windows_log windows_lock "Released the lock"
				return $RET
				;;
		*)
			windows_log windows_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;
	esac
}



################ windows functions











