#!/bin/bash
# this is the functions file for the cloud-plugin
CLOUD_MANAGER_LOCK_FILE=/var/run/openqrm/cloud-plugin.lock
CLOUD_MANAGER_LOCK_DELAY=5
CLOUD_MANAGER_LOCK_RETRY=100
CLOUD_MANAGER_LOCK_TIMEOUT=500
################ common cloud functions

# logs for cloud
function cloud_manager_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "cloud plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function cloud_manager_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $CLOUD_MANAGER_LOCK_FILE` ]; then
		mkdir -p `dirname $CLOUD_MANAGER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $CLOUD_MANAGER_LOCK_DELAY -r $CLOUD_MANAGER_LOCK_RETRY -l $CLOUD_MANAGER_LOCK_TIMEOUT $CLOUD_MANAGER_LOCK_FILE
				RET=$?
				cloud_manager_log cloud_manager_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $CLOUD_MANAGER_LOCK_FILE
				RET=$?
				cloud_manager_log cloud_manager_lock "Released the lock"
				return $RET
				;;
		*)
			cloud_manager_log cloud_manager_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ cloud functions






