#!/bin/bash
# init script for the openQRM nagios3 plugin
OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/include/openqrm-plugin-nagios3-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/etc/openqrm-plugin-nagios3.conf

HTPASSWD="htpasswd"
if [ -f /etc/SuSE-release ]; then
	HTPASSWD="htpasswd2"
fi

function openqrm_plugin_nagios3_start() {
	echo "Starting the openQRM nagios3-plugin"
	openqrm_plugin_nagios3_stop 1>/dev/null 2>&1
    # for debian/ubuntu we starting also ndoutils
    if [ -f /etc/debian_version ]; then
    	if [ -x /etc/init.d/ndoutils ]; then
            /etc/init.d/ndoutils start
        fi
    fi
	if [ -x /etc/init.d/nagios3 ]; then
		/etc/init.d/nagios3 start 1>/dev/null 2>&1
	elif [ -x /etc/init.d/nagios ]; then
		/etc/init.d/nagios start 1>/dev/null 2>&1
	else
		nagios_manager_lock release
		openqrm_post_event 0 "openqrm_plugin_nagios3_start" 3 "openqrm-plugin-nagios3" "Could not start Nagios. Init script not found !."
		exit 1
	fi
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios3/.running
	return 0
}


function openqrm_plugin_nagios3_stop() {
	echo "Stopping the openQRM nagios3-plugin"
    # for debian/ubuntu we stopping also ndoutils
    if [ -f /etc/debian_version ]; then
    	if [ -x /etc/init.d/ndoutils ]; then
            /etc/init.d/ndoutils stop
        fi
    fi
	if [ -x /etc/init.d/nagios3 ]; then
		/etc/init.d/nagios3 stop 1>/dev/null 2>&1
	elif [ -x /etc/init.d/nagios ]; then
		/etc/init.d/nagios stop 1>/dev/null 2>&1
	else
		nagios_manager_lock release
		openqrm_post_event 0 "openqrm_plugin_nagios3_stop" 3 "openqrm-plugin-nagios3" "Could not stop Nagios. Init script not found !."
		exit 1
	fi
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios3/.running
	return 0
}


function openqrm_plugin_nagios3_init() {
	echo "Initializing the openQRM nagios3-plugin"
    if ! $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios3/bin/openqrm-nagios-manager init; then
		nagios_manager_lock release
		openqrm_post_event 0 "openqrm_plugin_nagios3_stop" 3 "openqrm-plugin-nagios3" "Could not init the  Nagios3 plugin !."
        return 1
    fi
	return 0
}


function openqrm_plugin_nagios3_uninstall() {
	echo "Uninstalling the openQRM nagios3-plugin"
	openqrm_plugin_nagios3_stop
	# unlinking the web dir
	
	rm -rf $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios3
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-nagios3.tgz
	# restore old nagios htpasswd
    rm -f $NAGIOS_ETC_DIRECTORY/htpasswd.users
	cp -f $NAGIOS_ETC_DIRECTORY/htpasswd.users.bkp $NAGIOS_ETC_DIRECTORY/htpasswd.users
	# restore old nagios config.js
	cp -f /usr/share/nagios3/htdocs/config.js.bkp /usr/share/nagios3/htdocs/config.js
	# restore old nagios cgi.cfg
	cp -f $NAGIOS_ETC_DIRECTORY/cgi.cfg.bkp $NAGIOS_ETC_DIRECTORY/cgi.cfg
}



case "$1" in
	start)
		openqrm_plugin_nagios3_start
		;;
	stop)
		openqrm_plugin_nagios3_stop
		;;
	restart)
		openqrm_plugin_nagios3_stop
		sleep 1
		openqrm_plugin_nagios3_start
		;;
	init)
		openqrm_plugin_nagios3_init
		;;
	uninstall)
		openqrm_plugin_nagios3_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?


