#!/bin/bash
set -e

if [ -x "/etc/init.d/openqrm" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d openqrm uninstall || exit $?
	else
		/etc/init.d/openqrm uninstall || exit $?
	fi
fi

#DEBHELPER#

