#!/bin/bash

# linuxrc for the openQRM initrd
export SHELL=/bin/bash
PATH=/sbin:/bin:/usr/bin:/usr/sbin
export PATH

mount -t proc proc /proc
mkdir -p /dev/fd
ln -sf /proc/self/fd /dev/fd

#below is needed for pivot_root to work
echo 0x0100 > /proc/sys/kernel/real-root-dev

/bin/bash