#!/bin/bash
# init script for the openQRM lvm-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/etc/openqrm-plugin-lvm-storage.conf

function openqrm_plugin_lvm-storage_start() {
	echo "Starting the openQRM lvm-storage-plugin"
	openqrm_plugin_lvm-storage_stop 1>/dev/null 2>&1
}


function openqrm_plugin_lvm-storage_stop() {
	echo "Stopping the openQRM lvm-storage-plugin"
}

function openqrm_plugin_lvm-storage_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "lvm-storage: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "lvm-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM lvm-storage-plugin"
	openqrm_plugin_lvm-storage_stop
	openqrm_server_remove_storagetype $USERNAME $PASSWORD lvm-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/lvm-storage
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-lvm-storage.tgz
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/storagetype-capabilities.lvm-storage-menu.html
}

function openqrm_plugin_lvm-storage_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "lvm-storage: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "lvm-storage: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM lvm-storage-plugin"
	openqrm_server_add_storagetype $USERNAME $PASSWORD lvm-storage "Lvm Storage Server (nfs/iscsi/aoe)"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/lvm-storage
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/web/boot-service-lvm-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-lvm-storage.tgz
	# linking the storagetype-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/web/storagetype-capabilities.lvm-storage-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/storagetype-capabilities.lvm-storage-menu.html
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_lvm-storage_start
		;;
	stop)
		openqrm_plugin_lvm-storage_stop
		;;
	restart)
		openqrm_plugin_lvm-storage_stop
		sleep 1
		openqrm_plugin_lvm-storage_start
		;;
	init)
		openqrm_plugin_lvm-storage_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_lvm-storage_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




