#!/bin/bash
# init script for the openQRM lvm-storage-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/include/openqrm-plugin-lvm-storage-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/etc/openqrm-plugin-lvm-storage.conf

function openqrm_plugin_lvm-storage_start() {
	echo "Starting the openQRM lvm-storage-plugin"
	openqrm_plugin_lvm-storage_stop 1>/dev/null 2>&1
}


function openqrm_plugin_lvm-storage_stop() {
	echo "Stopping the openQRM lvm-storage-plugin"
}

function openqrm_plugin_lvm-storage_uninstall() {
	echo "Uninstalling the openQRM lvm-storage-plugin"
	openqrm_plugin_lvm-storage_stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-lvm-storage.tgz
}

function openqrm_plugin_lvm-storage_init() {
	echo "Initializing the openQRM lvm-storage-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/lvm-storage/web/boot-service-lvm-storage.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-lvm-storage.tgz
	
}


case "$1" in
	start)
		openqrm_plugin_lvm-storage_start
		;;
	stop)
		openqrm_plugin_lvm-storage_stop
		;;
	restart)
		openqrm_plugin_lvm-storage_stop
		sleep 1
		openqrm_plugin_lvm-storage_start
		;;
	init)
		openqrm_plugin_lvm-storage_init
		;;
	uninstall)
		openqrm_plugin_lvm-storage_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




