#!/bin/bash
# init script for the openQRM citrix-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix/include/openqrm-plugin-citrix-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix/etc/openqrm-plugin-citrix.conf

function openqrm_plugin_citrix_start() {
	echo "Starting the openQRM citrix-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix/.running
}


function openqrm_plugin_citrix_stop() {
	echo "Stopping the openQRM citrix-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix/.running
}

function openqrm_plugin_citrix_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "citrix: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "citrix: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM citrix-plugin"
	openqrm_plugin_citrix_stop
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD citrix
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD citrix-vm
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix
}

function openqrm_plugin_citrix_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "citrix: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "citrix: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM citrix-plugin"
	# adding virtualization type	
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD citrix "Citrix Host"
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD citrix-vm "Citrix VM"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/citrix/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/citrix
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_citrix_start
		;;
	stop)
		openqrm_plugin_citrix_stop
		;;
	restart)
		openqrm_plugin_citrix_stop
		sleep 1
		openqrm_plugin_citrix_start
		;;
	init)
		openqrm_plugin_citrix_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_citrix_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




