#!/bin/bash
# init script for the openQRM xen-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/include/openqrm-plugin-xen-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/etc/openqrm-plugin-xen.conf

function openqrm_plugin_xen_start() {
	echo "Starting the openQRM xen-plugin"
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/xen/.running
}


function openqrm_plugin_xen_stop() {
	echo "Stopping the openQRM xen-plugin"
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/xen/.running
}

function openqrm_plugin_xen_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "xen: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "xen: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM xen-plugin"
	openqrm_plugin_xen_stop
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD xen
	openqrm_server_remove_virtualization_type $USERNAME $PASSWORD xen-vm
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/xen
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-xen.tgz
	rm -rf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux/com32
}

function openqrm_plugin_xen_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "xen: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "xen: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM xen-plugin"
	# putting the mboot.c32 module in place
	mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux/com32/modules/
	if [ -f /usr/lib/syslinux/mboot.c32 ]; then
		cp -f /usr/lib/syslinux/mboot.c32 $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux/com32/modules/
	
	else
		echo "ERROR: Could not find mboot.c32 module for pxelinux/syslinux"
		echo "ERROR: Please copy it manually to $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux/com32/modules/"
		echo "ERROR: Could not find mboot.c32 module for pxelinux/syslinux" | logger
		echo "ERROR: Please copy it manually to $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/pxelinux/com32/modules/"  | logger
	fi
	# adding virtualization type	
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD xen "Xen Host"
	openqrm_server_add_virtualization_type $USERNAME $PASSWORD xen-vm "Xen VM"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/xen
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/web/boot-service-xen.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-xen.tgz
    # create stat dir
    mkdir -p $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/web/xen-stat
    chmod 777 $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/xen/web/xen-stat

}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_xen_start
		;;
	stop)
		openqrm_plugin_xen_stop
		;;
	restart)
		openqrm_plugin_xen_stop
		sleep 1
		openqrm_plugin_xen_start
		;;
	init)
		openqrm_plugin_xen_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_xen_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




