#!/bin/bash
# this is the functions file for the vmware-server2-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#
VMWARE_SERVER_LOCK_FILE=/var/run/openqrm/vmware-server2-plugin.lock
VMWARE_SERVER_LOCK_DELAY=5
VMWARE_SERVER_LOCK_RETRY=100
VMWARE_SERVER_LOCK_TIMEOUT=500
################ common vmware-server2 functions

# logs for vmware-server2
function vmware_server2_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "vmware-server2 plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function vmware_server2_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $VMWARE_SERVER_LOCK_FILE` ]; then
		mkdir -p `dirname $VMWARE_SERVER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $VMWARE_SERVER_LOCK_DELAY -r $VMWARE_SERVER_LOCK_RETRY -l $VMWARE_SERVER_LOCK_TIMEOUT $VMWARE_SERVER_LOCK_FILE
				RET=$?
				vmware_server2_log vmware_server_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $VMWARE_SERVER_LOCK_FILE
				RET=$?
				vmware_server2_log vmware_server_lock "Released the lock"
				return $RET
				;;
		*)
			vmware_server2_log vmware_server2_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ vmware-server2 functions






