#!/bin/bash
# openqrm-client	openQRM init script for the managed resources
#
# chkconfig: 345 98 19
# description: openQRM is the next generation Linux Data Center management

# support for LSB init scripts
### BEGIN INIT INFO
# Provides:
# Required-Start: $all
# Required-Stop: $all
# Default-Start:   3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: openQRM init script for the managed resources
# Description: openQRM init script for the managed resources
### END INIT INFO

PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH
LOCKFILE=/var/lock/subsys/openqrm
mkdir -p $(dirname $LOCKFILE)

export `eval cat /proc/cmdline`	
. /var/openqrm/openqrm-resource.conf
export OPENQRM_SERVER_BASE_DIR=$resource_basedir
. $resource_basedir/openqrm/include/openqrm-functions

function openqrm_client_start() {
	echo "Starting openQRM-client"

	openqrm_client_stop 1>/dev/null 2>&1
	# checks
	umount /initrd/lib/modules 1>/dev/null 2>&1
	umount /initrd/boot 1>/dev/null 2>&1
	umount /initrd/ 1>/dev/null 2>&1
	grep -q "/initrd" /proc/mounts && umount /initrd

	# start openqrm-execd
	$resource_basedir/openqrm/sbin/openqrm-exec-port-monitor $resource_ip $resource_execdport | $resource_basedir/openqrm/sbin/openqrm-execd &
	# start openqrm-monitord
	$resource_basedir/openqrm/sbin/openqrm-monitord &
	touch ${LOCKFILE}
}


function openqrm_client_stop() {
	echo "Stopping openQRM-client"
	# stop openqrm-execd
	killall openqrm-exec-port-monitor 1>/dev/null 2>&1
	killall openqrm-execd 1>/dev/null 2>&1
	killall openqrm-monitord 1>/dev/null 2>&1
	/bin/rm -f ${LOCKFILE}
}

function openqrm_client_status() {
	if [ -f ${LOCKFILE} ]; then
		echo "openQRM-client service is running"
	else
		echo "openQRM-client service is not running"
	fi
}



case "$1" in
	start)
		openqrm_client_start
		;;
	stop)
		openqrm_client_stop
		;;
	status)
		openqrm_client_status
		;;
	restart)
		openqrm_client_stop
		openqrm_client_start
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart}"
		exit 1
		;;
esac

