#!/bin/bash
# init script for the openQRM iscsi-deployment-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/include/openqrm-plugin-iscsi-deployment-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/etc/openqrm-plugin-iscsi-deployment.conf



function openqrm_plugin_iscsi-deployment_start() {
	echo "Starting the openQRM iscsi-deployment-plugin"
}


function openqrm_plugin_iscsi-deployment_stop() {
	echo "Stopping the openQRM iscsi-deployment-plugin"
}

function openqrm_plugin_iscsi-deployment_uninstall() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "iscsi-deployment: Please give a username to uninstall the plugin : "
		read USERNAME
		echo	
		echo -n "iscsi-deployment: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Uninstalling the openQRM iscsi-deployment-plugin"
	openqrm_plugin_iscsi-deployment_stop
	openqrm_server_remove_deployment_type $USERNAME $PASSWORD iscsi
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/iscsi-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.iscsi-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.iscsi-menu.html
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm
}

function openqrm_plugin_iscsi-deployment_init() {
	local USERNAME=$1
	local PASSWORD=$2
	if [ "$USERNAME" == "" ] && [ "$PASSWORD" == "" ]; then
		echo -n "iscsi-deployment: Please give a username to init the plugin : "
		read USERNAME
		echo	
		echo -n "iscsi-deployment: Please give the password for user $USERNAME : "
		read PASSWORD
		echo
	fi
	echo "Initializing the openQRM iscsi-deployment-plugin"
	openqrm_server_add_deployment_type $USERNAME $PASSWORD iscsi "Iscsi-root deployment"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/iscsi-deployment
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/web/root-mount.iscsi-deployment
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/web/root-mount.iscsi-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.iscsi-deployment
	# linking the image-menu
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/web/image-deployment-parameter.iscsi-menu.html $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/image-deployment-parameter.iscsi-menu.html
	# copying iscsid to boot-service dir
	cp -f `which iscsid` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying iscsiadm to boot-service dir
	cp -f `which iscsiadm` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	
}

USER=$2
PASS=$3

case "$1" in
	start)
		openqrm_plugin_iscsi-deployment_start
		;;
	stop)
		openqrm_plugin_iscsi-deployment_stop
		;;
	restart)
		openqrm_plugin_iscsi-deployment_stop
		sleep 1
		openqrm_plugin_iscsi-deployment_start
		;;
	init)
		openqrm_plugin_iscsi-deployment_init $USER $PASS
		;;
	uninstall)
		openqrm_plugin_iscsi-deployment_uninstall $USER $PASS
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




