#!/bin/bash
# init script for the openQRM iscsi-deployment-plugin

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/include/openqrm-plugin-iscsi-deployment-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/etc/openqrm-plugin-iscsi-deployment.conf


# TODO
# we must find a proper solution to start/stop 
# the plugin with correct user-authentication
# -> for now using openqrm user static

function openqrm_plugin_iscsi-deployment_start() {
	echo "Starting the openQRM iscsi-deployment-plugin"
	openqrm_server_add_deployment_type openqrm openqrm iscsi "Iscsi-root deployment"
}


function openqrm_plugin_iscsi-deployment_stop() {
	echo "Stopping the openQRM iscsi-deployment-plugin"
	openqrm_server_remove_deployment_type openqrm openqrm iscsi

}

function openqrm_plugin_iscsi-deployment_uninstall() {
	echo "Uninstalling the openQRM iscsi-deployment-plugin"
	openqrm_plugin_iscsi-deployment_stop
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.iscsi-deployment
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsid
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/iscsiadm
}

function openqrm_plugin_iscsi-deployment_init() {
	echo "Initializing the openQRM iscsi-deployment-plugin"
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/$OPENQRM_PLUGIN_NUMBER
	# linking the boot-service
	chmod +x $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/web/root-mount.iscsi-deployment
	ln -s $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/iscsi-deployment/web/root-mount.iscsi-deployment $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/root-mount.iscsi-deployment
	# copying iscsid to boot-service dir
	cp -f `which iscsid` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	# copying iscsiadm to boot-service dir
	cp -f `which iscsiadm` $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/
	
}


case "$1" in
	start)
		openqrm_plugin_iscsi-deployment_start
		;;
	stop)
		openqrm_plugin_iscsi-deployment_stop
		;;
	restart)
		openqrm_plugin_iscsi-deployment_stop
		sleep 1
		openqrm_plugin_iscsi-deployment_start
		;;
	init)
		openqrm_plugin_iscsi-deployment_init
		;;
	uninstall)
		openqrm_plugin_iscsi-deployment_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?




