#!/bin/bash
# openQRM mysql-specfic functions
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
	echo "ERROR: Please export OPENQRM_SERVER_BASE_DIR before sourcing $0"
	exit 1
fi

. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
# get full server config
openqrm_server_get_config
OPENQRM_DATABASE_INIT="$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/mysql/openqrm-mysql-init.sql"

OPENQRM_DATABASE_MAINTENANCE="$OPENQRM_SERVER_BASE_DIR/openqrm/etc/db/mysql/openqrm-mysql-maintenance"
OPENQRM_DATABASE_MAINTENANCE_FNAME=`basename $OPENQRM_DATABASE_MAINTENANCE`

if ! which mysql 1>/dev/null 2>&1; then
	echo "ERROR: Mysql client 'mysql' not installed/found on this system"
	exit 1
else
	export MYSQL_CLIENT=`which mysql`
fi
if ! which mysqldump 1>/dev/null 2>&1; then
	echo "ERROR: Mysql 'mysqldump' not installed/found on this system"
	exit 1
else
	export MYSQL_DUMP=`which mysqldump`
fi



function initialize_database() {
	# set the dbname in the sql init-script
	OPENQRM_DATABASE_INIT_TMP=/tmp/openqrm-mysql-init.sql
	cat $OPENQRM_DATABASE_INIT |	\
		sed -e "s/OPENQRM_DB/$OPENQRM_DATABASE_NAME/g" |	\
		sed -e "s/OPENQRM_SERVER_IP_ADDRESS/$OPENQRM_SERVER_IP_ADDRESS/g"	\
		> $OPENQRM_DATABASE_INIT_TMP

	echo "Initializing the openQRM-database"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER < $OPENQRM_DATABASE_INIT_TMP
		RET=$?
	else
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER < $OPENQRM_DATABASE_INIT_TMP
		RET=$?
	fi
	rm -f $OPENQRM_DATABASE_INIT_TMP

	# add the db maintenance to cron
	cat $OPENQRM_DATABASE_MAINTENANCE | sed -e "s#@@OPENQRM_SERVER_BASE_DIR@@#$OPENQRM_SERVER_BASE_DIR#g" > /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
	chmod +x /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
    if [ -x "/etc/init.d/cron" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d cron reload || exit $?
        else
            /etc/init.d/cron reload || exit $?
        fi
	elif [ -x "/etc/init.d/crond" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d crond reload || exit $?
        else
            /etc/init.d/crond reload || exit $?
        fi
    else
    	echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
    fi
	return $RET
}

function backup_database() {
	local SQL=$1
	echo "Creating backup of the openQRM-database at $SQL"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_DUMP -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME > $SQL
		RET=$?
	else
		$MYSQL_DUMP -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER  $OPENQRM_DATABASE_NAME > $SQL
		RET=$?
	fi
	return $RET

}

function restore_database() {
	local SQL=$1
	echo "Restoring the openQRM-database from $SQL"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME < $SQL
		RET=$?
	else
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER $OPENQRM_DATABASE_NAME < $SQL
		RET=$?
	fi
	return $RET

}

function drop_database() {
	echo "Dropping the openQRM-database"
	if [ -z "$OPENQRM_DATABASE_PASSWORD" ]; then
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		RET=$?
	else
		$MYSQL_CLIENT -u $OPENQRM_DATABASE_USER -p$OPENQRM_DATABASE_PASSWORD --host $OPENQRM_DATABASE_SERVER -e "drop database $OPENQRM_DATABASE_NAME" 1>/dev/null 2>&1
		RET=$?
	fi

	# remove maintenance cron job
	rm -f /etc/cron.daily/$OPENQRM_DATABASE_MAINTENANCE_FNAME
    if [ -x "/etc/init.d/cron" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d cron reload || exit $?
        else
            /etc/init.d/cron reload || exit $?
        fi
	elif [ -x "/etc/init.d/crond" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
            invoke-rc.d crond reload || exit $?
        else
            /etc/init.d/crond reload || exit $?
        fi
    else
    	echo "Could not find cron init script in /etc/init.d/. Please reload cron manually!"
    fi

	return $RET
}

case "$1" in
	init)
		initialize_database
		;;
	backup)
		backup_database $2
		;;
	restore)
		restore_database $2
		;;
	drop)
		drop_database
		;;
esac
