#!/bin/bash
# this is the functions file for the image-shelf-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#
IMAGE_SHELF_LOCK_FILE=/var/run/image-shelf/image-shelf-plugin.lock
IMAGE_SHELF_LOCK_DELAY=5
IMAGE_SHELF_LOCK_RETRY=100
IMAGE_SHELF_LOCK_TIMEOUT=500
################ common image-shelf functions

# logs for image-shelf
function image_shelf_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "image-shelf plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function image_shelf_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $IMAGE_SHELF_LOCK_FILE` ]; then
		mkdir -p `dirname $IMAGE_SHELF_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $IMAGE_SHELF_LOCK_DELAY -r $IMAGE_SHELF_LOCK_RETRY -l $IMAGE_SHELF_LOCK_TIMEOUT $IMAGE_SHELF_LOCK_FILE
				RET=$?
				image_shelf_log image_shelf_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $IMAGE_SHELF_LOCK_FILE
				RET=$?
				image_shelf_log image_shelf_lock "Released the lock"
				return $RET
				;;
		*)
			image_shelf_log image_shelf_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ image-shelf functions


function image_shelf_set_resolv_conf() {
	local image_path=$1
	if [ "$image_path" == "" ]; then
		exit 1
	fi
	if [ ! -d "$image_path" ]; then
		exit 1
	fi
	# backup orig
	if [ ! -f $image_path/etc/resolv.conf.image-shelf.bak ]; then
		cp -f $image_path/etc/resolv.conf $image_path/etc/resolv.conf.image-shelf.bak
	fi
	# try different options to find out the right nameservers and domain-name
	# dhcpd plugin
	if [ -f "$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/etc/dhcpd.conf" ]; then
		DOMAIN_NAME=`grep domain-name $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/etc/dhcpd.conf | grep -v domain-name-servers | awk {' print $3 '} | cut -d'"' -f2`
		NAME_SERVER=`grep domain-name-servers $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dhcpd/etc/dhcpd.conf | head -n1 | awk {' print $3 '} | sed -e "s/;//g"`
		echo "domain $DOMAIN_NAME" > $image_path/etc/resolv.conf
		echo "search $DOMAIN_NAME" >> $image_path/etc/resolv.conf
		echo "nameserver $NAME_SERVER" >> $image_path/etc/resolv.conf
		return 1
	fi
	# dns plugin
	if [ -f "$OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/etc/openqrm-plugin-dns.conf" ]; then
		. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/dns/etc/openqrm-plugin-dns.conf
		echo "domain $OPENQRM_SERVER_DOMAIN" > $image_path/etc/resolv.conf
		echo "search $OPENQRM_SERVER_DOMAIN" >> $image_path/etc/resolv.conf
		echo "nameserver $OPENQRM_SERVER_IP_ADDRESS" >> $image_path/etc/resolv.conf
		return 2
	fi

	# else copy openqrm-severs /etc/resolv.conf
	cp -f /etc/resolv.conf $image_path/etc/resolv.conf
	return 3

}



