#!/bin/bash
# This function gets called after writing the resource pxe-config file
# It re-writes the config localboot
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions


function local_server_assign_hook() {

	local OPENQRM_RESOURCE_ID=$1
	local OPENQRM_KERNEL_NAME=$2
	local OPENQRM_RESOURCE_PXELINUXCFG_FILE=$3
	local OPENQRM_RESOURCE_MAC=`echo $OPENQRM_RESOURCE_PXELINUXCFG_FILE | sed -e "s/01-//g" | sed -e "s/-/:/g"`

	if ! echo $OPENQRM_KERNEL_NAME | grep default 1>/dev/null; then
        if [ "$OPENQRM_KERNEL_NAME" == "resource$OPENQRM_RESOURCE_ID" ]; then
            echo "local-server-plugin: Running assign hook with $OPENQRM_RESOURCE_ID $OPENQRM_KERNEL_NAME $OPENQRM_RESOURCE_PXELINUXCFG_FILE"
            echo "local-server-plugin: Running assign hook with $OPENQRM_RESOURCE_ID $OPENQRM_KERNEL_NAME $OPENQRM_RESOURCE_PXELINUXCFG_FILE" | logger

            # get more infos about the resource
            openqrm_get_resource_parameter $OPENQRM_RESOURCE_MAC
            if [ "$resource_capabilities" == "local-server" ]; then
                openqrm_server_set_boot local $resource_id $resource_mac $resource_ip
            fi
        else
            echo "local-server-plugin: Resource $OPENQRM_RESOURCE_ID netbooting. Skipping local-assign" | logger
        fi
	fi

}

