#!/bin/bash

KVM=`which kvm`
if [ "$KVM" == "" ]; then
	echo "ERROR: kvm ist not installed on this system !" | logger
	exit 1
fi
# source the component config files
VM_CONF_DIR=`dirname $0`
VM_CONF_DIR=`cd $VM_CONF_DIR && pwd && cd - 1>/dev/null`
VM_NAME=`basename $VM_CONF_DIR`
. $VM_CONF_DIR/ram
. $VM_CONF_DIR/disk
. $VM_CONF_DIR/net
. $VM_CONF_DIR/vnc

echo "KVM vm $VM_NAME starting up ..." | logger
screen -dmS $KVM_VM_MAC $KVM $KVM_VM_DISK -m $KVM_VM_RAM -boot n $KVM_VM_NET -vnc $KVM_VM_VNC