#!/bin/bash

KVM=`which kvm`
if [ "$KVM" == "" ]; then
	echo "ERROR: kvm ist not installed on this system !" | logger
	exit 1
fi
echo "KVM vm @@KVM_VM_NAME@@ starting up ..." | logger
screen -dmS @@KVM_VM_NAME@@ $KVM @@KVM_DISK_CONF@@ -m @@OPENQRM_RESOURCE_RAM@@ -boot n -net nic,macaddr=@@KVM_VM_MAC@@,model=e1000 -net tap -vnc 127.0.0.1:@@KVM_VM_VNC@@