#!/bin/bash
# this is the functions file for the nagios2-plugin

# logs for nagios2
function nagios2_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "nagios2 plug-in" "$COMPONENT : $MESSAGE"
}

