#!/bin/bash
# init script for the openQRM nagios2 plugin
OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/include/openqrm-plugin-nagios2-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/etc/openqrm-plugin-nagios2.conf

function openqrm_plugin_nagios2_start() {
	echo "Starting the openQRM nagios2-plugin"
	openqrm_plugin_nagios2_stop 1>/dev/null 2>&1
	/etc/init.d/nagios2 start 1>/dev/null 2>&1
	return 0
}


function openqrm_plugin_nagios2_stop() {
	echo "Stopping the openQRM nagios2 plugin"
	/etc/init.d/nagios2 stop 2>&1
	return 0
}


function openqrm_plugin_nagios2_init() {
	echo "Initializing the openQRM nagios2 plugin"
	

	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios2

	return 0
}


function openqrm_plugin_nagios2_uninstall() {
	echo "Uninstalling the openQRM nagios2 plugin"
	openqrm_plugin_nagios2_stop
	# unlinking the web dir
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios2
}



case "$1" in
	start)
		openqrm_plugin_nagios2_start
		;;
	stop)
		openqrm_plugin_nagios2_stop
		;;
	restart)
		openqrm_plugin_nagios2_stop
		sleep 1
		openqrm_plugin_nagios2_start
		;;
	init)
		openqrm_plugin_nagios2_init
		;;
	uninstall)
		openqrm_plugin_nagios2_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?


