#!/bin/bash
# init script for the openQRM nagios2 plugin
OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/include/openqrm-plugin-nagios2-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/etc/openqrm-plugin-nagios2.conf

HTPASSWD="htpasswd"
if [ -f /etc/SuSE-release ]; then
	HTPASSWD="htpasswd2"
fi

function openqrm_plugin_nagios2_start() {
	echo "Starting the openQRM nagios2-plugin"
	openqrm_plugin_nagios2_stop 1>/dev/null 2>&1
	/etc/init.d/nagios2 start 1>/dev/null 2>&1
	touch $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios2/.running
	return 0
}


function openqrm_plugin_nagios2_stop() {
	echo "Stopping the openQRM nagios2-plugin"
	/etc/init.d/nagios2 stop 2>&1
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios2/.running
	return 0
}


function openqrm_plugin_nagios2_init() {
	echo "Initializing the openQRM nagios2-plugin"
	CURRENT_DIR=`pwd`
	# linking the web dir
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/web $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios2
	# link the boot-service
	ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/web/boot-service-nagios2.tgz $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-nagios2.tgz
	# link the public key
	if [ ! -f /root/.ssh/id_dsa.pub ]; then 
		echo "ERROR: Please create a plublic key for the root user before using the Nagios plugin"
		sleep 4
	fi
	cp -f /root/.ssh/id_dsa.pub $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrmserver_public_key
	chmod 644 $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrmserver_public_key
	# Nagios Single-Sign-On
	# First backup original nagios.password
    mv /etc/nagios2/htpasswd.users /etc/nagios2/htpasswd.users.bkp
    # link openqrm .htaccess to nagios
    ln -s $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/.htpasswd /etc/nagios2/htpasswd.users
    # change nagiosadmin 2 openqrm for accessing nagios-gui
    sed -i -e 's/nagiosadmin/openqrm/' /etc/nagios2/cgi.cfg 
    # 	
	# Add openqrm to nagios-contacts - not perfect, but working first :)
	# sed -i "s/root/openqrm/g" /etc/nagios2/conf.d/contacts_nagios2.cfg
	# theme nagios
	. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/etc/build.conf/nuvola.conf
	mkdir -p $OPENQRM_TEMP_DIR/nuvola_inst/
	tar -C $OPENQRM_TEMP_DIR/nuvola_inst/ -zxf $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/nagios2/theme/nagios-nuvola-$OPENQRM_SOURCE_VERSION.tar.gz
	cp -r $OPENQRM_TEMP_DIR/nuvola_inst/html/* /usr/share/nagios2/htdocs/
	rm -rf $OPENQRM_TEMP_DIR/nuvola_inst/
 	# Fix WebGUI for Debian
 	sed -i "s/nagios\/cgi-bin/nagios2\/cgi-bin/g"  /usr/share/nagios2/htdocs/config.js
 	cd $CURRENT_DIR
	return 0
}


function openqrm_plugin_nagios2_uninstall() {
	echo "Uninstalling the openQRM nagios2-plugin"
	openqrm_plugin_nagios2_stop
	# unlinking the web dir
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/base/plugins/nagios2
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/boot-service-nagios2.tgz
	rm -f $OPENQRM_WEBSERVER_DOCUMENT_ROOT/openqrm/boot-service/openqrmserver_public_key
	# restore old nagios htpasswd
	mv /etc/nagios2/htpasswd.users.bkp /etc/nagios2/htpasswd.users
}



case "$1" in
	start)
		openqrm_plugin_nagios2_start
		;;
	stop)
		openqrm_plugin_nagios2_stop
		;;
	restart)
		openqrm_plugin_nagios2_stop
		sleep 1
		openqrm_plugin_nagios2_start
		;;
	init)
		openqrm_plugin_nagios2_init
		;;
	uninstall)
		openqrm_plugin_nagios2_uninstall
		;;
	*)
		echo "Usage: $0 {start|stop|restart|init|uninstall}"
		exit 1

esac
exit $?


