#!/bin/bash
# this is the functions file for the tftpd-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#


function openqrm_plugin_tftpd_update_pmtu() {
	#if pmtu is disabled we want to reenable it so tftp trasfer don't get stuck
	#if the are mtu problems on the network.
	pmtu_disable_status=$(cat /proc/sys/net/ipv4/ip_no_pmtu_disc)
	if [ "$pmtu_disable_status" != "0" ] ; then
		cat 0 > /proc/sys/net/ipv4/ip_no_pmtu_disc
	fi
}
