#!/bin/bash
# this is the functions file for the citrix-plugin
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

CITRIX_SERVER_LOCK_FILE=/var/run/openqrm/citrix-plugin.lock
CITRIX_SERVER_LOCK_DELAY=5
CITRIX_SERVER_LOCK_RETRY=100
CITRIX_SERVER_LOCK_TIMEOUT=500

CITRIX_XE_BINARY=/usr/sbin/xe


################ common citrix functions

# logs for citrix
function citrix_log() {
	local COMPONENT=$1
	shift
	local MESSAGE=$@
	logger -i -t "citrix plug-in" "$COMPONENT : $MESSAGE"
}


# locking function
function citrix_lock() {
	local COMMAND=$1
	local RET=1
	
	if [ ! -d `dirname $CITRIX_SERVER_LOCK_FILE` ]; then
		mkdir -p `dirname $CITRIX_SERVER_LOCK_FILE`
	fi
	case "$COMMAND" in
		aquire)
				lockfile -s $CITRIX_SERVER_LOCK_DELAY -r $CITRIX_SERVER_LOCK_RETRY -l $CITRIX_SERVER_LOCK_TIMEOUT $CITRIX_SERVER_LOCK_FILE
				RET=$?
				citrix_log citrix_lock "Aquired the lock"
				return $RET
				;;
		release)
				/bin/rm -f $CITRIX_SERVER_LOCK_FILE
				RET=$?
				citrix_log citrix_lock "Released the lock"
				return $RET
				;;
		*)
			citrix_log citrix_lock "No such command. Try 'aquire' or 'release'"
			return 1
			;;	
	esac
}



################ citrix functions

