#!/bin/bash

# this is a hook function for the kernel-creation phase

function citrix_kernel_hook() {

	local KERNEL_NAME=$1
	local KERNEL_VERSION=$2
	local KERNEL_LOCATION=$3
	local KERNEL_TYPE=$4

	echo "citrix-plugin: Running citrix_kernel_hook $KERNEL_NAME $KERNEL_VERSION $KERNEL_LOCATION $KERNEL_TYPE"
	echo "citrix-plugin: Running citrix_kernel_hook $KERNEL_NAME $KERNEL_VERSION $KERNEL_LOCATION $KERNEL_TYPE" | logger
	echo "citrix-plugin: basedir = $OPENQRM_SERVER_BASE_DIR" | logger

	if ls $KERNEL_LOCATION/boot/citrix*.gz 1>/dev/null 2>&1; then
		echo "citrix-plugin: Found Xen-hypervisor at $KERNEL_LOCATION/boot/"
		echo "citrix-plugin: Copying Xen-hypervisor to $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/"
		for CITRIXFILE in `ls $KERNEL_LOCATION/boot/citrix*.gz`; do
			if [ ! -h $CITRIXFILE ]; then
				cp -f $CITRIXFILE $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/citrix-$KERNEL_NAME.gz
			fi
		done
		# linking the initrd to the boot-service dir
		if [ ! -f $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/initrd-$KERNEL_NAME.img ]; then
			echo "citrix-plugin: Linking $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/initrd-$KERNEL_NAME.img to $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/initrd-$KERNEL_NAME.img"
			ln -sf $OPENQRM_SERVER_BASE_DIR/openqrm/tftpboot/boot/initrd-$KERNEL_NAME.img $OPENQRM_SERVER_BASE_DIR/openqrm/web/boot-service/initrd-$KERNEL_NAME.img
		fi
	fi
	
	
}