#!/bin/bash
# this is the boot-service init script for the VMware-server hosts

OPENQRM_SERVER_BASE_DIR=$(pushd $(dirname $0)/../../../../.. > /dev/null; echo $PWD; popd > /dev/null)
. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-functions
. $OPENQRM_SERVER_BASE_DIR/openqrm/plugins/linux-vserver/include/openqrm-plugin-linux-vserver-functions
if [ -f $OPENQRM_RESOURCE_PARAMETER_FILE ]; then
	. $OPENQRM_RESOURCE_PARAMETER_FILE
	OPENQRM_SERVER_IP=$resource_openqrmserver
elif [ -f $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf ]; then
	. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
	. $OPENQRM_SERVER_BASE_DIR/openqrm/include/openqrm-server-functions
	openqrm_server_get_config
	OPENQRM_SERVER_IP=$OPENQRM_SERVER_IP_ADDRESS
fi

# only run on vmware-server hosts
which vmware-cmd 1>/dev/null 2>&1 || exit 0


function vmware-server_start() {
	echo "Starting the openQRM vmware-server-plugin"
	vmware-server_stop 1>/dev/null 2>&1
}


function vmware-server_stop() {
	echo "Stopping the openQRM vmware-server-plugin"
}





case "$1" in
	start)
		vmware-server_start
		;;
	stop)
		vmware-server_stop
		;;
	restart)
		vmware-server_stop
		sleep 1
		vmware-server_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1

esac
exit $?













