#!/bin/bash
#  openQRM-rexecd, a openQRM-daemon for remote exection of openQRM-commands

if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
	OPENQRM_SERVER_BASE_DIR=$(dirname $0)/../..
	OPENQRM_SERVER_BASE_DIR=$(pushd $OPENQRM_SERVER_BASE_DIR > /dev/null && echo $PWD && popd > /dev/null)
fi
export OPENQRM_SERVER_BASE_DIR
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
DB_IDLE=5
DB_TIMEOUT=5
OPENQRM_COMMAND_QUEUE="$OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/openqrm-queue"
WHOAMI=`whoami`

# parse commandline args
while [ $# -ne 0 ]; do
	case "$1" in
		-i)
			RESOURCE_IP=$2
			shift
			;;
		-c)
			shift
			OPENQRM_COMMAND=$@
			shift
			;;			
	esac
	shift
done

FULL_COMMAND="$OPENQRM_SERVER_BASE_DIR/openqrm/bin/dbclient -I $DB_IDLE -K $DB_IDLE -y -i $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key -p $OPENQRM_EXEC_PORT root@$RESOURCE_IP \"$OPENQRM_SERVER_BASE_DIR/openqrm/bin/openqrm-cmd $OPENQRM_COMMAND\""
# echo "openQRM engine (as $WHOAMI) queuing : $FULL_COMMAND" | logger
echo "$FULL_COMMAND" >> $OPENQRM_COMMAND_QUEUE


