#!/bin/bash
#  openQRM-exec, an openQRM-util for remote exection of openQRM-commands
#
# This file is part of openQRM.
#
# openQRM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2
# as published by the Free Software Foundation.
#
# openQRM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with openQRM.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2009, Matthias Rechenburg <matt@openqrm.com>
#

if [ "$OPENQRM_SERVER_BASE_DIR" == "" ]; then
	OPENQRM_SERVER_BASE_DIR=$(dirname $0)/../..
	OPENQRM_SERVER_BASE_DIR=$(pushd $OPENQRM_SERVER_BASE_DIR > /dev/null && echo $PWD && popd > /dev/null)
fi
export OPENQRM_SERVER_BASE_DIR
. $OPENQRM_SERVER_BASE_DIR/openqrm/etc/openqrm-server.conf
DB_IDLE=0
DB_TIMEOUT=10
OPENQRM_COMMAND_QUEUE="$OPENQRM_SERVER_BASE_DIR/openqrm/var/spool/openqrm-queue"
WHOAMI=`whoami`

# parse commandline args
while [ $# -ne 0 ]; do
	case "$1" in
		-i)
			RESOURCE_IP=$2
			shift
			;;
		-t)
			COMMAND_TOKEN=$2
			shift
			;;
		-c)
			shift
			OPENQRM_COMMAND=$@
			shift
			;;			
	esac
	shift
done
# checks
if [ "$RESOURCE_IP" == "0.0.0.0" ]; then
    echo "openQRM-exec ERROR: Not running command on invalid ip address 0.0.0.0" | logger
fi
if [ "$RESOURCE_IP" == "" ]; then
    echo "openQRM-exec ERROR: Not running command on empty ip address" | logger
fi
# run
FULL_COMMAND="$OPENQRM_SERVER_BASE_DIR/openqrm/bin/dbclient -K $DB_TIMEOUT -y -i $OPENQRM_SERVER_BASE_DIR/openqrm/etc/dropbear/dropbear_rsa_host_key -p $OPENQRM_EXEC_PORT root@$RESOURCE_IP \"$OPENQRM_SERVER_BASE_DIR/openqrm/bin/openqrm-cmd $OPENQRM_COMMAND\""
# echo "openQRM engine (as $WHOAMI) queuing : $FULL_COMMAND" | logger
echo "$FULL_COMMAND" >> $OPENQRM_COMMAND_QUEUE.$COMMAND_TOKEN


